default: &default
 adapter: postgresql
 encoding: unicode
 host: db
 username: postgres
 password: password
 pool: 5

development:
 <<: *default
 database: plmhealthoneapp_development


test:
 <<: *default
 database: plmhealthoneapp_test