FL:
  class: "Webscraper::States::FloridaScraper"
  url: "https://mqa-internet.doh.state.fl.us/mqasearchservices/healthcareproviders"
CA:
  class: "Webscraper::States::CaliforniaScraper"
  url: "https://search.dca.ca.gov/"
AZ:
  class: "Webscraper::States::ArizonaScraper"
  url: "https://azbomprod.azmd.gov/GLSuiteWeb/Clients/AZBOM/public/WebVerificationSearch.aspx"
AL:
  class: "Webscraper::States::AlabamaScraper"
  url: "https://abn.alabama.gov/applications/LicenseLookup.aspx"
AK:
  class: "Webscraper::States::AlaskaScraper"
  url: "https://www.commerce.alaska.gov/cbp/main/Search/Professional"
AR:
  class: "Webscraper::States::ArkansasScraper"
  url: "https://www.armedicalboard.org/public/verify/default.aspx"
CO:
  class: "Webscraper::States::ColoradoScraper"
  url: "https://apps.colorado.gov/dora/licensing/Lookup/LicenseLookup.aspx"
CT:
  class: "Webscraper::States::ConnecticutScraper"
  url: "https://www.elicense.ct.gov/Lookup/LicenseLookup.aspx"
DE:
  class: "Webscraper::States::DelawareScraper"
  url: "https://dpronline.delaware.gov/verification/"
DC:
  class: "Webscraper::States::DistrictOfColumbiaScraper"
  url: "https://dchealth.dc.gov/"
FL:
  class: "Webscraper::States::FloridaScraper"
  url: "https://mqa-internet.doh.state.fl.us/mqasearchservices/healthcareproviders"
GA:
  class: "Webscraper::States::GeorgiaScraper"
  url: "https://gadch.mylicense.com/verification/Search.aspx?facility=Y"
HI:
  class: "Webscraper::States::HawaiiScraper"
  url: "https://cca.hawaii.gov/"
ID:
  class: "Webscraper::States::IdahoScraper"
  url: "https://ibol.idaho.gov/IBOL/"
IL:
  class: "Webscraper::States::IllinoisScraper"
  url: "https://www.idfpr.com/"
IN:
  class: "Webscraper::States::IndianaScraper"
  url: "https://mylicense.in.gov/verification/"
IA:
  class: "Webscraper::States::IowaScraper"
  url: "https://mmr.iowa.gov/LicenseLookup/"
KS:
  class: "Webscraper::States::KansasScraper"
  url: "https://www.kansas.gov/"
KY:
  class: "Webscraper::States::KentuckyScraper"
  url: "https://kbn.ky.gov/"
LA:
  class: "Webscraper::States::LouisianaScraper"
  url: "https://www.lsbme.la.gov/" 
ME:
  class: "Webscraper::States::MaineScraper"
  url: "https://www.maine.gov/"
MD:
  class: "Webscraper::States::MarylandScraper"
  url: "https://www.mbp.state.md.us/"
MA:
  class: "Webscraper::States::MassachusettsScraper"
  url: "https://www.mass.gov/orgs/board-of-registration"
MI:
  class: "Webscraper::States::MichiganScraper"
  url: "https://www.michigan.gov/lara/"
MN:
  class: "Webscraper::States::MinnesotaScraper"
  url: "https://mn.gov/boards/"
MS:
  class: "Webscraper::States::MississippiScraper"
  url: "https://www.dmh.ms.gov/"
MO:
  class: "Webscraper::States::MissouriScraper"
  url: "https://pr.mo.gov/"
MT:
  class: "Webscraper::States::MontanaScraper"
  url: "https://bsd.dli.mt.gov/"
NE:
  class: "Webscraper::States::NebraskaScraper"
  url: "https://www.nebraska.gov/"
NV:
  class: "Webscraper::States::NevadaScraper"
  url: "https://www.nv.gov/"
NH:
  class: "Webscraper::States::NewHampshireScraper"
  url: "https://www.oplc.nh.gov/"
NJ:
  class: "Webscraper::States::NewJerseyScraper"
  url: "https://www.njconsumeraffairs.gov/"
NM:
  class: "Webscraper::States::NewMexicoScraper"
  url: "https://www.rld.state.nm.us/"
NY:
  class: "Webscraper::States::NewYorkScraper"
  url: "https://eservices.ny.gov/"
NC:
  class: "Webscraper::States::NorthCarolinaScraper"
  url: "https://www.ncmedboard.org/"
ND:
  class: "Webscraper::States::NorthDakotaScraper"
  url: "https://www.ndhealth.gov/"
OH:
  class: "Webscraper::States::OhioScraper"
  url: "https://med.ohio.gov/"
OK:
  class: "Webscraper::States::OklahomaScraper"
  url: "https://www.okmedicalboard.org/"
OR:
  class: "Webscraper::States::OregonScraper"
  url: "https://omb.oregon.gov/search"
PA:
  class: "Webscraper::States::PennsylvaniaScraper"
  url: "https://www.pals.pa.gov/#!/page/search"
RI:
  class: "Webscraper::States::RhodeIslandScraper"
  url: "https://healthri.mylicense.com/Verification/"
SC:
  class: "Webscraper::States::SouthCarolinaScraper"
  url: "https://scmedicalboard.org/"
SD:
  class: "Webscraper::States::SouthDakotaScraper"
  url: "https://dlr.sd.gov/"
TN:
  class: "Webscraper::States::TennesseeScraper"
  url: "https://www.tn.gov/"
TX:
  class: "Webscraper::States::TexasScraper"
  url: "https://www.tmb.state.tx.us/"
UT:
  class: "Webscraper::States::UtahScraper"
  url: "https://dopl.utah.gov/"
VT:
  class: "Webscraper::States::VermontScraper"
  url: "https://secure.professionals.vermont.gov/prweb/PRServletCustom/app/NGLPGuestUser_/V9csDxL3sXkkjMC_FR2HrA*/!STANDARD?UserIdentifier=LicenseLookupGuestUser"
VA:
  class: "Webscraper::States::VirginiaScraper"
  url: "https://dhp.virginiainteractive.org/Lookup/Index"
VI: 
  class: "Webscraper::States::VirginIslandsScraper"
  url: "https://secure.dlca.vi.gov/license/Asps/Search/License_search.aspx"
WA:
  class: "Webscraper::States::WashingtonScraper"
  url: "https://www.doh.wa.gov/"
WV:
  class: "Webscraper::States::WestVirginiaScraper"
  url: "https://wvdhhr.org/"
WI:
  class: "Webscraper::States::WisconsinScraper"
  url: "https://www.dhs.wisconsin.gov/"
WY:
  class: "Webscraper::States::WyomingScraper"
  url: "https://www.wyomedboard.org/"
