class CreatePracticeLocations < ActiveRecord::Migration[7.0]
  def change
    create_table :practice_locations do |t|
      t.string :location
      t.string :legal_name
      t.string :address1
      t.string :address2
      t.string :city
      t.string :state_id
      t.string :zip_code
      t.string :phone_number
      t.string :fax_number
      t.string :email
      t.string :group_tax_number
      t.string :group_npi_number
      t.boolean :have_group_tax_number
      t.datetime :group_npi_number_effective_date
      t.string :languages_speak
      t.string :languages_write
      t.string :interpreters_available
      t.string :contact_first_name
      t.string :contact_middle_name
      t.string :contact_last_name
      t.string :contact_suffix
      t.string :contact_title
      t.string :contact_phone_number
      t.string :contact_ext
      t.string :contact_fax_number
      t.string :contact_email
      t.time :monday_time_start
      t.time :monday_time_end
      t.boolean :monday_split_day
      t.boolean :monday_closed
      t.time :tuesday_time_start
      t.time :tuesday_time_end
      t.boolean :tuesday_split_day
      t.boolean :tuesday_closed
      t.time :wednesday_time_start
      t.time :wednesday_time_end
      t.boolean :wednesday_split_day
      t.boolean :wednesday_closed
      t.time :thursday_time_start
      t.time :thursday_time_end
      t.boolean :thursday_split_day
      t.boolean :thursday_closed
      t.time :friday_time_start
      t.time :friday_time_end
      t.boolean :friday_split_day
      t.boolean :friday_closed
      t.time :saturday_time_start
      t.time :saturday_time_end
      t.boolean :saturday_split_day
      t.boolean :saturday_closed
      t.time :sunday_time_start
      t.time :sunday_time_end
      t.boolean :sunday_split_day
      t.boolean :sunday_closed
      t.string :comment
      t.string :telephone_coverage
      t.string :telephone_coverage_type
      t.string :telephone_number_after_hours
      t.string :telephone_number_ext
      t.string :pa_practice_status
      t.string :pa_by_health_plan
      t.string :pa_limitations
      t.string :pa_gender_limitations
      t.integer :pa_minimum_age
      t.integer :pa_maximum_age
      t.boolean :pa_min_max_not_applicable
      t.string :pa_other_limitations
      t.string :ada_accessibility
      t.string :ada_wrp
      t.string :disabled_other_services
      t.string :disabled_other_services_wrp
      t.string :public_transportation
      t.string :public_transportation_wrp
      t.string :laboratory_services
      t.string :laboratory_services_wrp
      t.string :clia_waiver
      t.string :clia_waiver_wrp
      t.string :clia_waiver_expiration_date
      t.string :clia_certificate
      t.string :clia_certificate_wrp
      t.string :clia_certificate_expiration_date
      t.string :radiology_services
      t.string :radiology_services_xray
      t.string :radiology_services_fda
      t.string :anesthesia_administered
      t.string :additional_procedures

      t.timestamps
    end
  end
end
