class AddColumnstoPracticeInformations < ActiveRecord::Migration[7.0]
  def change
   add_column :practice_informations, :suite_mail_stop, :integer
   add_column :practice_informations, :country, :string
   add_column :practice_informations, :office_manager, :string
   add_column :practice_informations, :office_manager_phone_number, :integer
   add_column :practice_informations, :office_manager_fax_number, :integer
   add_column :practice_informations, :gnc_tax_id_number, :integer
   add_column :practice_informations, :name_affiliated_with_tax_id, :integer
   add_column :practice_informations, :federal_tax_id, :integer
   add_column :practice_informations, :name_affiliated_with_tax_id2, :integer
   add_column :practice_informations, :number_of_patients_seen_weekly, :integer
   add_column :practice_informations, :total_number_of_patients_in_your_practice, :integer
   add_column :practice_informations, :number_of_medicare_patients, :integer
   add_column :practice_informations, :ahp_first_name, :string
   add_column :practice_informations, :ahp_last_name, :string
   add_column :practice_informations, :ahp_suffix, :string
   add_column :practice_informations, :ahp_type_of_practitioner, :string
   add_column :practice_informations, :ahp_address, :string
   add_column :practice_informations, :ahp_suite_mail_stop, :string
   add_column :practice_informations, :ahp_additional_address, :string
   add_column :practice_informations, :ahp_city, :string
   add_column :practice_informations, :ahp_county, :string
   add_column :practice_informations, :ahp_state_province, :string
   add_column :practice_informations, :ahp_zip_postal_code, :integer
   add_column :practice_informations, :ahp_country, :string
   add_column :practice_informations, :ahp_state_license_number, :integer
   add_column :practice_informations, :wpsnp_ratio1, :string
   add_column :practice_informations, :wpsnp_midwife_ratio1, :string
   add_column :practice_informations, :wpsnp_physician_assistant_ratio1, :string
   add_column :practice_informations, :pep_first_name, :string
   add_column :practice_informations, :pep_last_name, :string
   add_column :practice_informations, :pep_suffix, :string
   add_column :practice_informations, :pep_type_of_practitioner, :string
   add_column :practice_informations, :pep_state_license_number, :integer
   add_column :practice_informations, :olcm_first_name, :string
   add_column :practice_informations, :olcm_middle_name, :string
   add_column :practice_informations, :olcm_last_name, :string
   add_column :practice_informations, :olcm_suffix, :string
   add_column :practice_informations, :olcm_type_of_practitioner, :string
   add_column :practice_informations, :olcm_specialty, :string
   add_column :practice_informations, :stf_languages_you_speak, :string
   add_column :practice_informations, :stf_languages_you_read, :string
   add_column :practice_informations, :stf_languages_you_write, :string
   add_column :practice_informations, :stf_languages_you_specify, :string  
   add_column :practice_informations, :radiology_services, :boolean  
   add_column :practice_informations, :allergy_injections, :boolean  
   add_column :practice_informations, :age_appropriate_immunizations, :boolean
   add_column :practice_informations, :osteopathic_manipulations, :boolean
   add_column :practice_informations, :ekg, :boolean
   add_column :practice_informations, :allergy_skin_tests, :boolean
   add_column :practice_informations, :flexible_sigmoidoscopy, :boolean
   add_column :practice_informations, :iv_hydration_treatments, :boolean
   add_column :practice_informations, :care_of_minor_lacerations, :boolean
   add_column :practice_informations, :routine_Office_gynecology, :boolean
   add_column :practice_informations, :tympanometry_audiometry_tests, :boolean
   add_column :practice_informations, :cardiac_stress_tests, :boolean
   add_column :practice_informations, :pulmonary_function_tests, :boolean
   add_column :practice_informations, :drawing_blood, :boolean
   add_column :practice_informations, :asthma_treatments, :boolean
   add_column :practice_informations, :physical_therapies, :boolean
   add_column :practice_informations, :other_including_surgical_services, :string
   add_column :practice_informations, :clinical_services_you_perform, :string
   add_column :practice_informations, :clinical_services_you_do_not_perform, :string
   add_column :practice_informations, :practice_limited_to_a_certain_age_specify, :string
   add_column :practice_informations, :practice_limited_to_a_specific_gender_select, :string
   add_column :practice_informations, :other_limitations, :string
   add_column :practice_informations, :computer_office_use, :string
   add_column :practice_informations, :Operating_system_use, :string
   add_column :practice_informations, :which_network, :string
   add_column :practice_informations, :which_one, :string
   add_column :practice_informations, :local, :boolean
   add_column :practice_informations, :regional, :boolean
   add_column :practice_informations, :conscious_sedation, :boolean
   add_column :practice_informations, :general, :boolean
   add_column :practice_informations, :perform_surgery_explain, :string
   add_column :practice_informations, :anesthesia_first_name, :string
   add_column :practice_informations, :anesthesia_last_name, :string
   add_column :practice_informations, :anesthesia_suffix, :string
   add_column :practice_informations, :anesthesia_practitioner_title, :string
   add_column :practice_informations, :anesthesia_specify, :string
   add_column :practice_informations, :anesthesia_classa, :boolean
   add_column :practice_informations, :anesthesia_classb, :boolean
   add_column :practice_informations, :anesthesia_classc, :boolean
   add_column :practice_informations, :aaaasf, :boolean
   add_column :practice_informations, :state_department, :boolean
   add_column :practice_informations, :imq_aaahc, :boolean
   add_column :practice_informations, :medicare_certification, :boolean
   add_column :practice_informations, :tmqc, :boolean
   add_column :practice_informations, :acl_pls_explain, :string
   add_column :practice_informations, :billing_name, :string
   add_column :practice_informations, :tax_id, :boolean
   add_column :practice_informations, :type_of_service_provided, :string
   add_column :practice_informations, :clia_certificate_number, :integer
   add_column :practice_informations, :certificate_expiration_date, :datetime
   add_column :practice_informations, :please_list_all_x_ray_certifications, :string
   add_column :practice_informations, :please_list_all_other_certificates_of_participation, :string
   add_column :practice_informations, :answering_service, :boolean
   add_column :practice_informations, :voice_mail_with_answering_service, :boolean
   add_column :practice_informations, :voice_mail_with_other_instruction, :boolean
   add_column :practice_informations, :answering_service_company, :string
   add_column :practice_informations, :fax_number_service, :integer
   add_column :practice_informations, :mailing_address, :string
   add_column :practice_informations, :suite_dept_mail_stop, :string
   add_column :practice_informations, :additional_address_servise, :string
   add_column :practice_informations, :state_province, :string
   add_column :practice_informations, :zip_postal_code, :boolean
   add_column :practice_informations, :country_name, :string
   add_column :practice_informations, :cpgi_group_name, :string
   add_column :practice_informations, :cpgi_facility, :string
   add_column :practice_informations, :cpgi_street_address, :string
   add_column :practice_informations, :cpgi_suite_dept_mail_stop, :string
   add_column :practice_informations, :cpgi_additional_address, :string
   add_column :practice_informations, :cpgi_city, :string
   add_column :practice_informations, :cpgi_county, :string
   add_column :practice_informations, :cpgi_state_province, :string
   add_column :practice_informations, :cpgi_zip_postal_code, :string
   add_column :practice_informations, :cpgi_country, :string
   add_column :practice_informations, :cpgi_phone_number, :integer
   add_column :practice_informations, :cpgi_fax_number, :integer
   add_column :practice_informations, :cpgi_email_address, :string
   add_column :practice_informations, :building, :boolean
   add_column :practice_informations, :parking, :boolean
   add_column :practice_informations, :restroom, :boolean
   add_column :practice_informations, :handicapped_accessible_explain, :string
   add_column :practice_informations, :text_telephony_tty, :boolean
   add_column :practice_informations, :american_sign_language_asl, :boolean
   add_column :practice_informations, :mental_physical_impairment_services, :boolean
   add_column :practice_informations, :Other, :boolean
   add_column :practice_informations, :service_disabled_explain, :string
   add_column :practice_informations, :bus, :boolean
   add_column :practice_informations, :subway, :boolean
   add_column :practice_informations, :regional_train, :boolean
   add_column :practice_informations, :bus_other, :boolean
   add_column :practice_informations, :public_transportation_explain, :string
   add_column :practice_informations, :if_other_please_explain, :string
   add_column :practice_informations, :group_npi, :integer
   add_column :practice_informations, :please_list_any_comments, :string
   add_column :practice_informations, :mon_time_from, :time
   add_column :practice_informations, :mon_time_to, :time
   add_column :practice_informations, :mon_closed, :boolean, default: false
   add_column :practice_informations, :tue_time_from, :time
   add_column :practice_informations, :tue_time_to, :time
   add_column :practice_informations, :tue_closed, :boolean, default: false
   add_column :practice_informations, :wed_time_from, :time
   add_column :practice_informations, :wed_time_to, :time
   add_column :practice_informations, :wed_closed, :boolean, default: false
   add_column :practice_informations, :thu_time_from, :time
   add_column :practice_informations, :thu_time_to, :time
   add_column :practice_informations, :thu_closed, :boolean, default: false
   add_column :practice_informations, :fri_time_from, :time
   add_column :practice_informations, :fri_time_to, :time
   add_column :practice_informations, :fri_closed, :boolean, default: false
   add_column :practice_informations, :sat_time_from, :time
   add_column :practice_informations, :sat_time_to, :time
   add_column :practice_informations, :sat_closed, :boolean, default: false
   add_column :practice_informations, :sun_time_from, :time
   add_column :practice_informations, :sun_time_to, :time
   add_column :practice_informations, :sun_closed, :boolean, default: false
  end
end
