class AddColumnsToPracticeInformations < ActiveRecord::Migration[7.0]
  def change
    add_column :practice_informations, :country, :string
    add_column :practice_informations, :office_manager, :string
    add_column :practice_informations, :manager_phone_number, :string
    add_column :practice_informations, :manager_fax_number, :string
    add_column :practice_informations, :back_office_phone_number, :string
    add_column :practice_informations, :type_of_practice, :string
    add_column :practice_informations, :mail_stop, :string
    add_column :practice_informations, :hospital_based_department_name, :string
    add_column :practice_informations, :practice_type, :string
    add_column :practice_informations, :group_name, :string
    add_column :practice_informations, :group_number_with_tax_id, :string
    add_column :practice_informations, :name_affiliated_with_tax_id, :string
    add_column :practice_informations, :federal_tax_id, :string
    add_column :practice_informations, :number_of_patients_weekly, :string
    add_column :practice_informations, :total_number_of_patients, :string
    add_column :practice_informations, :total_medicare_patients, :string
    add_column :practice_informations, :total_medical_medicaid_patients, :string
    add_column :practice_informations, :is_ccs, :boolean
    add_column :practice_informations, :is_chdp, :boolean
    add_column :practice_informations, :any_allied_health_practitioner, :boolean
    add_column :practice_informations, :allied_health_practitioner_first_name, :string
    add_column :practice_informations, :allied_health_practitioner_last_name, :string
    add_column :practice_informations, :allied_health_practitioner_suffix, :string
    add_column :practice_informations, :allied_health_practitioner_type_of_practitioner, :string
    add_column :practice_informations, :allied_health_practitioner_mail_stop, :string
    add_column :practice_informations, :allied_health_practitioner_address, :string
    add_column :practice_informations, :allied_health_practitioner_address2, :string
    add_column :practice_informations, :allied_health_practitioner_city, :string
    add_column :practice_informations, :allied_health_practitioner_county, :string
    add_column :practice_informations, :allied_health_practitioner_state, :string
    add_column :practice_informations, :allied_health_practitioner_zip_code, :string
    add_column :practice_informations, :allied_health_practitioner_country, :string
    add_column :practice_informations, :allied_health_practitioner_state_license, :string
    add_column :practice_informations, :allied_health_practitioner_state_license_number, :string
    add_column :practice_informations, :allied_health_practitioner_listed_as_pcp, :boolean
    add_column :practice_informations, :physician_to_nurse_ratio, :integer
    add_column :practice_informations, :physician_to_assistant_ratio, :integer
    add_column :practice_informations, :is_employing_any_personal_practitioner, :boolean
    add_column :practice_informations, :is_licensed_member_in_practice, :boolean
    add_column :practice_informations, :is_staff_speak_any_foreign_language, :boolean
    add_column :practice_informations, :radiology_services, :string
    add_column :practice_informations, :allergy_injections, :string
    add_column :practice_informations, :age_approriate_immunizations, :string
    add_column :practice_informations, :osteopathic_manipulations, :string
    add_column :practice_informations, :ekg, :string
    add_column :practice_informations, :allergy_skin_tests, :string
    add_column :practice_informations, :flexible_sigmoidoscopy, :string
    add_column :practice_informations, :iv_hydration_treatments, :string
    add_column :practice_informations, :care_of_minor_lacerations, :string
    add_column :practice_informations, :routine_office_gynecology, :string
    add_column :practice_informations, :tympanometry_audiometry_tests, :string
    add_column :practice_informations, :cardiac_stress_tests, :string
    add_column :practice_informations, :pulmonary_function_tests, :string
    add_column :practice_informations, :drawing_blood, :string
    add_column :practice_informations, :asthma_treatmeant, :string
    add_column :practice_informations, :physical_therapies, :string
    add_column :practice_informations, :have_other_surgical_services, :boolean
    add_column :practice_informations, :other_surgical_services, :string
    add_column :practice_informations, :clinical_services_performed_not_typically_associated, :string
    add_column :practice_informations, :clinical_services_not_performed_typically_associated, :string
    add_column :practice_informations, :has_practice_limit_age, :boolean
    add_column :practice_informations, :practice_limit_age_from, :string
    add_column :practice_informations, :practice_limit_age_to, :string
    add_column :practice_informations, :has_limited_gender, :boolean
    add_column :practice_informations, :limited_gender, :string
    add_column :practice_informations, :other_limitations, :string
    add_column :practice_informations, :computer_office_ibm, :string
    add_column :practice_informations, :computer_office_mac, :string
    add_column :practice_informations, :computer_office_has_other, :boolean
    add_column :practice_informations, :computer_office_other, :string
    add_column :practice_informations, :os_office_wind_98, :string
    add_column :practice_informations, :os_office_wind_95, :string
    add_column :practice_informations, :os_office_wind_me, :string
    add_column :practice_informations, :os_office_wind_2000, :string
    add_column :practice_informations, :os_office_wind_nt, :string
    add_column :practice_informations, :os_office_wind_xp, :string
    add_column :practice_informations, :os_office_mac, :string
    add_column :practice_informations, :has_os_office_other, :boolean
    add_column :practice_informations, :os_office_other, :string
    add_column :practice_informations, :has_computer_has_internet_access, :boolean
    add_column :practice_informations, :does_participate_edi, :boolean
    add_column :practice_informations, :edi_network, :string
    add_column :practice_informations, :has_practice_management_software, :boolean
    add_column :practice_informations, :practice_management_software, :string
    add_column :practice_informations, :does_perform_surgery, :boolean
    add_column :practice_informations, :anesthesia_local, :boolean
    add_column :practice_informations, :anesthesia_regional, :boolean
    add_column :practice_informations, :anesthesia_conscious_sedation, :boolean
    add_column :practice_informations, :anesthesia_general, :boolean
    add_column :practice_informations, :anesthesia_other, :boolean
    add_column :practice_informations, :anesthesia_other_value, :string
    add_column :practice_informations, :anesthesia_none, :boolean
  end
end
