class AppTracker < ApplicationRecord
  belongs_to :practitioner

  OWNER_LIST = [
    'Geller, Marilyn',
    'Frie, Adam',
    'Ho, Anne',
    'Johannes, Ashlet',
    'Kriti, Animesh',
    'Louie, Ashley',
    'Minster, Andrew',
    'Banerjee, Ankita',
    'Rai, Anisha',
    'Raney, Attie',
    'Viscarra, Ashley',
    'Craft, Caitlin',
    'Diec, Chris',
    'Magee, Chiquita',
    'Navarro, Cameron',
    'Syravong, Chris',
    'Batitin, Democrito',
    'Chhetri, Deepika',
    'Espinoza, Davis',
    'Ops, Dev',
    'Randolph, Dawson',
    'To, Diana',
    'Polins, Erica',
    'Chen, Felicia',
    'Gupta, Gaurav',
    'Chung, Hannah',
    'Whittaker, Holly',
    'Preciado, Irma',
    'Albrigo, John',
    'Bautista, Julie',
    'Blanco, Jennifer',
    'Capps, Joel',
    'Davis, Joseph',
    'Dykstra, Janice',
    'Lo, Jan',
    'Lopez, Jo Ann',
    'Morrison, Joe',
    'Smith, John',
    'Triplett, James',
    'Udasan, Jelamie',
    'Atwal, Kulvinder',
    'Bose, Kohinoor',
    'Delois Fannie, Kim',
    'B, Kenneth',
    'Garcia, Kimberly',
    'Kelly, Keeley',
    'Kirks, Kristen',
    'Nin, Khris',
    'Ramos, Kimberly',
    'Aranda, Louis',
    'Eldridge, Laura',
    'Han, Lawrence',
    'Hill, latanya',
    'Lerma, Linda',
    'Neiber, Lisa',
    'Post, Lana',
    'Tran, Lawrence',
    'Shaw, Mamata',
    'Banerjee, Munmun',
    'Calapre, Marylyn',
    'Camps, Michaela',
    'Chettri, Meena',
    ', Michael',
    'Ghosh, Maitri',
    'Gray, Michael',
    'Huskie, Michelle',
    'Lampitoc, Mark',
    'Oberg, Melanie',
    'Templar, Morgan',
    'Urdiales, Michael',
    'Winkler, Michelle',
    'Alikhan, Noor',
    'Naimuddin, Sk',
    'Chigarapalle, Navi',
    'Yadav, Nibedita',
    'Saephan, Penny',
    'Seidel, Peter',
    'Alexander, Robert',
    'Rivera, Randy',
    'Balsara, Ramin',
    'Garza, Rosalinda',
    'Harris, Richard',
    'Mata, Richard',
    'Moeller, Rachelle',
    'Rodriguez, Rene',
    'Ruiz, Ricardo',
    'Sampson, Ray',
    'Sarkar, Sanjana',
    'Bhuyan, Sushmita',
    'Burrell, Stevon',
    'Lodh, Shib',
    'Chatterjee, Siddhartha',
    'Kohman, Susan',
    'Martinez, Sandra',
    'Mchale, Sue',
    'Mukherjee, Soumik',
    'Reddy, Shwetha',
    'Schaedler, Stephanie',
    'Schmidt, Stepheni',
    'Sitt, Swati',
    'Skinner, Stephen',
    'Toone, Skyler',
    'Das, Suchna',
    'Paul, Suparno',
    'Pati, Supramit',
    'Banerjee, Swagata',
    'Winkler, Shelly',
    'Brady, Tracey',
    'Dasgupta, Trishnendu',
    'Benero, Abegail',
    'Gualberto, Angelina',
    'Dela Cruz, Mark Angelo',
    'Cabudsan, Arnel',
    'Bagtas, Arries',
    'Cervantes, Jeffrey',
    'Codera, Charmine Grace', 
    'Mendoza, Cherry',
    'Montenegro, Christian Rey',
    'Salvaleon, Ciara',
    'Mabini, Dhea Rose',
    'Lanuza, Faith', 
    'Simine, Gari Csyrl', 
    'Pascual, Gene',
    'Agbayani, Geraldin',
    'Hagos, Gerry',
    'Gocoyo, Joseph',
    'Rendon, Hanelee', 
    'Baldemor, Hanelyn', 
    'Peroso, Jahzel',
    'Hiloma, Jannver Ruzzel', 
    'Relatado, Jason',
    'Encinas, Jerrick', 
    'Arenas, Jerwin',
    'Lising, Jess Francis',
    'Contreras, Jester',
    'Bahoy, Jeric Ryan',
    'Gallanito, Jhaira', 
    'Sangkad, Johana', 
    'Rivera, Jomar',
    'Reyes, Jonathan',
    'Liamzon, Joseph Angelo',
    'Agustino, Joyce',
    'Garbin, Kristine Joy',
    'Tagle, Jennyrose', 
    'Velasco, Jufell Velasco',
    'Guillar, Karl alexander',
    'Valezuela, Keith Harvey',
    'Pilapil, Kerwin Mark',
    'Malittay, Sheryl',
    'Kriss',
    'Lucagbo, Kyndle Marie',
    'Garbida, Larry',
    'Bautista, Lloyd Darwin',
    'Elan, Lorie Ann',
    'Pelayo, Mae',
    'Punis, Marielle',
    'Sapaula, Angelica Marie',
    'Salmamon, Marlon',
    'Cruz, Maurene',
    'Baguhin, Michael',
    'Tome, Mike',
    'Bandoy, Nathaniel',
    'Cabanacan, Nick Vincent',
    'Canda, Nikki',
    'Carmen, Norivel',
    'Azupardo, John Paulo',
    'Faller, Ralfh Lawrence',
    'Rivera, Randy',
    'Locsin, Raymund',
    'Timario, Reynaville',
    'Varquez, Rey Angelo',
    'Joting, Roe Jun', 
    'Nicolas, Rolando',
    'Rivera, Ryan',
    'Sy, Michelle', 
    'Test, Test',
    'Dayon, Mariz',
    'Ledesma, Vener', 
    'Correa, Zenaida',
    'Kihdze, Tobias',
    'Mathurin, Tassan',
    'Mcbride, Terri',
    'Mizsak, Tracy',
    'Wagner, Tammy',
    'macsbarango, victoria',
    'Backus, William',
    'Oglukyan, Zaven'
  ]

  def self.master_issue_list
    [
      'Board Certification Not Received',
      'Board Certification Not Verified',
      'CDS Not Received',
      'CDS Not Verified',
      'DEA Copy Not Received',
      'DEA Expiring / Expired',
      'DEA Not Received',
      'DEA Not Verified',
      'DEA Retired',
      'DEA/CDS Finding',
      'Disclosure Explanation Not Received',
      'Disclosure Questions Not Received',
      'Disclosure: DEA',
      'Disclosure: Hospital Privileges',
      'Disclosure: Medicare/Medicaid',
      'Education Not Received',
      'Education Not Verified',
      'Employment Gap Response Not Received',
      'Facility - No PAR Hospital',
      'Five year Carrier History Not Received',
      'Five Year Claims History Not Received',
      'Five Year Claims History Not Verified',
      'Incomplete App: Admitting Services',
      'Incomplete App: Affiliations',
      'Incomplete App: Area of Specialties',
      'Incomplete App: Certificate/Registration',
      'Incomplete App: Continuing Education Requirement',
      'Incomplete App: Directory Specialty Listing',
      'Incomplete App: Employment Information',
      'Incomplete App: Professional Associations and Organizations',
      'Incomplete App: Specialty/Board Certification',
      'Incomplete App: Health Care Entity',
      'Incomplete Application',
      'Insufficient Coverage',
      'License copy not received',
      'License Expiring / Expired',
      'License Finding',
      'License Not Received',
      'License Not Verified',
      'Malpractice Face Sheet Not Received',
      'Medicare Opt Out',
      'Narrative Not Received',
      'No Office in Batch State',
      'NPDB Finding',
      'NPI Number Not Received',
      'On Grievance Sheet',
      'OPM/OIG Finding',
      'Other - Client Provided Documentation',
      'Ownership Form Not Received',
      'Primary Hospital Not Received',
      'Primary Hospital Not Verified',
      'Professional Liability Addendum Not Signed/Dated',
      'Professional Liability Expired',
      'Professional Liability Information Addendum Not Received',
      'Release Not Received',
      'SAM Finding',
      'Signature Date Expired',
      'State Mandated Application Not Received',
      'Subcontractor Ownership Form Not Signed or Dated',
      'Ten Year Claims History Not Verified',
      'Training Not Received',
      'Training Not Verified',
      'Unable to Match NPI in NPPES Registry',
      'W-9 Form Not Received',
      'Work History For Past Five Years Not Received',
      'Work History From Medical School to Present Not Received'
    ]
  end

  def self.master_review_list
    [
      'CDS Expiring/Expired',
      'Claims History',
      'Claims History-1 or more cases greater than $100,000 each in previous 5 years',
      'Claims History-1-3 cases between $50,000 and $100,000 during previous 5 years',
      'Claims History-1-4 closed claims in previous 5 years all under $50,000 each',
      'Claims History-5+ closed claims in previous 5 years all under $50,000 each',
      'Claims History-Death',
      'Claims History-Death in Past 5 Years',
      'Date of Birth Inconsistent',
      'DEA Expiring/Expired',
      'Disclosure Response Discrepancy with Source Response',
      'Education Date Inconsistent',
      'Education Finding',
      'Employment Gap',
      'Expiring: Board Certification',
      'Facility Not Accredited/CMS Certified',
      'Foreign Education',
      'Graduation Date Inconsistent',
      'History of Loss of Admitting Facility Privileges or Disciplinary Action',
      'History of Loss of License and/or Felony Convictions',
      'Inability to Perform Essential Functions of Position',
      'Inconsistent Privileges Information',
      'Inconsistent Product Type',
      'Inconsistent Provider type to CVC data',
      'Insufficient Liability',
      'License Expiring/Expired',
      'No Admitting Arrangement',
      'No DEA',
      'No License in Practice State',
      'No PAR Hospital',
      'No/Expiring Professional Liability Coverage',
      'Not Boarded As Stated in Application',
      'Not Trained in Specialty',
      'Other Disclosure Finding',
      'PAR Hospital Finding',
      'PAR Specialty Not Verified',
      'Past Practice Without Malpractice Coverage',
      'Present Illegal Use of Drugs',
      'Private Practice',
      'Self-Reported Claims History',
      'SSN Discrepancy in CVC Data',
      'Training Date Inconsistent',
      'Training Finding',
      'WC Not Received'
    ]
  end
end
