class Certification < ApplicationRecord
  belongs_to :provider_attest
  has_many :rva_informations, dependent: :destroy

  CERTIFICATION_TYPE = [
    "ABA",
    "AC",
    "ACU",
    "ADC",
    "AGN",
    "AHP",
    "AMB",
    "ANP",
    "APN",
    "ARNP",
    "ARRT",
    "AUD",
    "BA",
    "BCaBA ",
    "BCBA",
    "BCO",
    "BSW",
    "CAADC",
    "CADC",
    "CAT",
    "CCDC",
    "CCS",
    "CDA",
    "CFA",
    "CLC",
    "CLD",
    "CLS",
    "CM",
    "CMHP",
    "CNA",
    "CNIM",
    "CNM",
    "CNP",
    "CNS",
    "COMT",
    "COT",
    "CP",
    "CPhT",
    "CPRM",
    "CRNA",
    "CRNP",
    "CRT",
    "CSP",
    "CST",
    "CSW",
    "DA",
    "DC",
    "DDS",
    "DDS, MD",
    "DH",
    "DMD",
    "DO",
    "Doula",
    "DP-C",
    "DPM",
    "DT",
    "EdD",
    "EFM",
    "EMT",
    "EPT",
    "FAC",
    "Facility",
    "FNP",
    "HAD",
    "Hospital",
    "LAC",
    "LADC ",
    "LALDC",
    "LBSW",
    "LCPC",
    "LCSW",
    "LEP",
    "LLBSW",
    "LLMSW",
    "LLP",
    "LLPC",
    "LMFT",
    "LMSW",
    "LMT",
    "LN",
    "LP",
    "LPC",
    "LPN",
    "LSA",
    "LSW",
    "LVN",
    "MA",
    "MBBS",
    "MD",
    "MFCC",
    "MFCC/MFT",
    "MFT",
    "MH",
    "MHC",
    "MPT",
    "MRT",
    "MS",
    "MSc",
    "MSSW",
    "MSW",
    "MT",
    "MW",
    "NC",
    "ND",
    "NEU",
    "NMF",
    "NMW",
    "NP",
    "NPF",
    "NRCMA",
    "OD",
    "OPT",
    "OrthoT",
    "OT",
    "Other",
    "OTR",
    "PA",
    "PAA",
    "PAC",
    "PAO",
    "Paramedic",
    "PC",
    "PHA",
    "Pharmacy",
    "PharmD",
    "PharmT",
    "PhD",
    "PHN",
    "PMHNP",
    "PN",
    "PNP",
    "PPCNP",
    "PRC",
    "PSS",
    "PsyD",
    "PT",
    "PTA",
    "PTNL",
    "QBHP",
    "QIDP",
    "QMHP",
    "RCP",
    "RD",
    "RDA",
    "RDH",
    "RDMS",
    "REPT",
    "RMA",
    "RN",
    "RNFA",
    "RPSGT",
    "RPT",
    "RRT",
    "RT",
    "RXN",
    "SAPS",
    "SATS",
    "SLD",
    "SLP",
    "SP",
    "SST",
    "Supplier",
    "TLLP",
    "WHCNP",
    "WHNP",
    "X-Ray Tech"
  ]

  ISSUING_AGENCY = [
    "AAMA",
    "ABPTS",
    "American Academy of Nurse Practitioners",
    "American Academy of Physician Assistants",
    "American Association of Critical Care Nurses",
    "American Association of Nurse Anesthetists",
    "American Midwifery Certification Board",
    "American Nephrology Nurses' Association",
    "American Nurses Credentialing Center",
    "ARRT or American Registry of Radiologic Technologists",
    "Elephant Circle",
    "GEORGIA COMPOSITE MEDICAL BOARD",
    "HCCPA",
    "Michigan Certification Board for Addiction Professionals",
    "Nation Commission of Certification of Physician Assistants",
    "National Association of Health Professionals",
    "National Board for Certification of Orthopaedic Physician Assistants",
    "National Certification Corporation",
    "National Certification for Credentialing of Physician Assistants",
    "National Certification for Credentialing PHysician Assistants",
    "National Certification of Physician Assistants",
    "National Cmmission on Certification of Physician Assistants",
    "National Comission on Certification of Physician Assistants",
    "national commision of certification of physician assistants",
    "National Commision on Certification of Physician Assistance",
    "National Commision on Certification of Physician Assistant",
    "National Commision on Certification of Physician Assistants",
    "National Commission on Certification of Physician Assistants",
    "National Commission Certification Physician Assistants",
    "National Commission for Certification of Physician Assistant",
    "National Commission of Certificate of Physician Assistants",
    "NATIONAL COMMISSION OF CERTIFICATION OF PA'S",
    "NATIONAL COMMISSION OF CERTIFICATION OF PHYSICIAN ASSISTANTS",
    "National Commission of Certification of Physicians Assistants",
    "National Commission of Physican Assistants",
    "National Commission of Physician Assistants",
    "national commission of physicians assistants",
    "National Commission on Ceritfication of Physician Assistants",
    "National Commission on Cert of PA's",
    "National Commission On Cert of Physician Assistants",
    "National Commission on Certification fo Physician Assistants",
    "National Commission on Certification for Physician Assistant",
    "National Commission on Certification for Physician Assistants",
    "National Commission on Certification of PA",
    "National Commission on Certification of PA's",
    "National Commission on Certification of Physican Assistants",
    "National Commission on Certification of Physician Assistance",
    "National Commission on certification of Physician Assistant",
    "National Commission on Certification of Physician Assistants",
    "National Commission on Certification of Physicians",
    "National Commission on Certification of Physicians Assistants",
    "National Commission on Certification of Physician's Assistants",
    "National Commission on certification of Pysician Assistants",
    "National Commission on Certification PA's",
    "National Commission on Certifications of Physicans Assistants",
    "National Commission on Credentialing of Physician Assistants",
    "National Committee on Certification of Physician Assistants",
    "Natioonal Commission on Certification of Physician Assistants",
    "NCAA",
    "NCCPA",
    "NCCPA - PANRE",
    "NCCPA, National Comm on Cert PA's",
    "selected="">Nephrology Nursing Certification Commission",
    "Oregon Medical Board",
    "Pediatric Nursing Certification Board",
    "Pharmacy Technician Certification Board",
    "Physician Assistant",
    "Physician Assistants and Advanced Practice Nursing Providers",
    "University of North Dakota Grand Falls"
  ]

  CERTIFICATION_STATUS = [
    "Admissable",
    "Board Certificate Status",
    "Cancelled",
    "Certified",
    "Eligible",
    "Expired",
    "Not Certified",
    "Qualified",
    "Retired",
    "Revoked",
    "Unable to Verify"
  ]
end
