class ClientOrganization < ApplicationRecord
	def address = "#{address1} #{address2}"

	PRIMARY_SERVICE = [
		"Air Ambulance",
		"Alcohol/Chemical Dependency",
		"Ambulance",
		"Ambulatory Surgery Center",
		"Ancillary",
		"Anesthesiology",
		"Artificial Eye Service",
		"Audiology",
		"Behavioral Health",
		"Birthing Center",
		"Birthing Rooms",
		"Blood Transfusion",
		"Brain Injury Rehabilitation",
		"Cancer Center",
		"Cardiac Care Unit",
		"Cardiac Center",
		"Cardiac Monitoring Service",
		"Cardiovascular Surgery",
		"Chemical Dependency Hospital",
		"Chemical Dependency Outpatient Facility",
		"Child Protection Center",
		"Chiropractic",
		"Chronic Disease Management",
		"Convenience Care Clinic",
		"CORF's",
		"CT Scanner",
		"Cytology Lab",
		"Diabetes Education Services",
		"Diabetic Durable Medical Equipment",
		"Diagnostic Facility",
		"Dialysis",
		"Dialysis Center",
		"Dialysis Supplies",
		"Dietitian-Lipids Only",
		"Drug Screening Site",
		"Durable Medical Equipment",
		"Electromyography Services",
		"Emergency Department",
		"Emergency Medicine",
		"Emergency Medicine-Pediatric",
		"Endoscopy Center",
		"ESRD",
		"Family Planning",
		"Federally Qualified Health Centers",
		"General Acute Care Hospital",
		"Genetic Testing Laboratory",
		"Health Department",
		"Hearing Aid, Sales &amp; Repair",
		"Hearing Therapy",
		"HHA's",
		"Home Health",
		"Home Health Agency",
		"Home Infusion",
		"Home Infusion Pharmaceuticals",
		"Home Infusion Therapy for HIV &amp; Transplant Patient Only",
		"Home IV Infusion Agency",
		"Hospice",
		"Hospices",
		"Hospital",
		"Hyperbaric/Undersea Treatment Center",
		"Infertility Clinic",
		"Inpatient Chemical Dependency Treatment Center",
		"Inpatient Psychiatric Treatment Center",
		"Intensive Care",
		"Internal Medicine",
		"Interpreter-sign Language",
		"Laboratory",
		"Labs",
		"Lactation Consultation",
		"Lithotripter",
		"Long Term Care Facility",
		"Lymphedema Clinic Services",
		"Mammography",
		"Mastectomy Supplies",
		"Maternity Management Service",
		"Medical Imaging",
		"Mental Health",
		"Mental Health Hospital",
		"Minute Clinics",
		"MRI",
		"Neonatal Intensive Care Unit (NICU)",
		"Non-Emergency Transportation",
		"Nursing Service",
		"Nutritionist",
		"Obstetrical Home Care Services",
		"Occupational Medicine",
		"Occupational Therapy",
		"Occupational Therapy - Pediatric",
		"Oncology Center",
		"Open MRI",
		"Optometry",
		"Organ Transplant",
		"Orthopaedics Surgery",
		"Orthotics",
		"Ostomy Supplies",
		"Other",
		"Outpatient Facility",
		"Outpatient Surgery",
		"output diabetes self mgt training",
		"Pathology",
		"Pediatric Home Health Agency",
		"Pediatric Hospital",
		"Pediatric Rehabilitation Hospital",
		"PET Scan",
		"Pharmacy",
		"Pharmacy, Specialty",
		"Physical Therapy",
		"Physical Therapy - Pediatric",
		"Physical, Speech, Occup Therapy",
		"portable x-ray suppliers",
		"Portable X-ray Supplies",
		"Prenatal Services",
		"Prosthetics",
		"Prosthetics/Orthotics",
		"Psychiatric",
		"Psychiatric Hospital",
		"Psychiatric Outpatient",
		"Psychiatric Pediatric",
		"PT/SP-OP",
		"Radiation Oncology",
		"Radiology",
		"Rehabilitation",
		"Rehabilitation Hospital",
		"Rehabilitation Inpatient",
		"Rehabilitation Physical Therapy",
		"Rehabilitation Speech Pathology",
		"Rehabilitation Therapy Facility",
		"Rural Health Clinic/Federally Qualified Health Clinic",
		"Rural Health Clinics",
		"Skilled Nursing",
		"Skilled Nursing Facility",
		"Sleep Disorders",
		"Specialty Care Hospital - Cancer",
		"Specialty Care Hospital - Pediatric Rehabilitation",
		"Specialty Care Hospital - Respiratory",
		"Specialty Hospital",
		"Speech Therapy",
		"Speech Therapy - Pediatric",
		"Speech/Hearing Therapy",
		"Subacute Care",
		"Surgery Center",
		"Surgical Supplies",
		"TENS Device",
		"Ultra Sound",
		"Urgent Care",
		"Urgent Care Clinic",
		"Ventilation Therapy",
		"Vision",
		"Walk In Clinics",
		"Womens Facility",
		"Wound Care Facility"
	]

	FACILITY_TYPE = [
		"AC",
		"ACU",
		"ADC",
		"AHP",
		"ANP",
		"APN",
		"ARNP",
		"AUD",
		"BCBA",
		"BCO",
		"BT",
		"C",
		"CCDC",
		"CDA",
		"CLC",
		"CLD",
		"CNA",
		"CNIM",
		"CNM",
		"CNP",
		"CNS",
		"COMT",
		"COT",
		"CP",
		"CRNA",
		"CRNP",
		"CRT",
		"CSP",
		"CST",
		"CSW",
		"DA",
		"DC",
		"DDS",
		"DDS, MD",
		"DMD",
		"DO",
		"DPM",
		"DT",
		"EdD",
		"EMT",
		"EPT",
		"FAC",
		"Facility",
		"FNP",
		"HAD",
		"Hospital",
		"LAC",
		"LADC ",
		"LALDC",
		"LCPC",
		"LCSW",
		"LEP",
		"LIMHP",
		"LISW",
		"LMFT",
		"LMT",
		"LN",
		"LP",
		"LPC",
		"LPN",
		"LSA",
		"LSW",
		"LVN",
		"MA",
		"MBBS",
		"MD",
		"MFCC",
		"MFCC/MFT",
		"MFT",
		"MH",
		"MHC",
		"MHP",
		"MPT",
		"MRT",
		"MS",
		"MSc",
		"MSSW",
		"MSW",
		"MT",
		"MW",
		"NC",
		"ND",
		"NEU",
		"NMF",
		"NMW",
		"NP",
		"NPF",
		"OD",
		"OPT",
		"OrthoT",
		"OT",
		"Other",
		"OTR",
		"PA",
		"PAA",
		"PAC",
		"PAO",
		"Paramedic",
		"PC",
		"PCC",
		"PHA",
		"Pharmacy",
		"PharmD",
		"PharmT",
		"PhD",
		"PHN",
		"PsyD",
		"PT",
		"PTA",
		"RCP",
		"RD",
		"RDA",
		"RDMS",
		"REPT",
		"RMA",
		"RN",
		"RNFA",
		"RPSGT",
		"RPT",
		"RRT",
		"RT",
		"SLD",
		"SLP",
		"SP",
		"WHCNP"
	]

end