class ProviderNpdb < ApplicationRecord
  PRIMARY_KEY_ROW_NAMES = ['ProviderAttestID','ProviderEducationID']

  belongs_to :provider_attest

  validates :provider_attest_id, presence: true

  before_validation :set_provider_attest

  PRACTITIONER_TYPE = [
    "Accountant",
    "Acupuncturist",
    "Adult Care Facility Administrator",
    "ADULT DAY CARE FACILITY",
    "AMBULANCE SERVICE/TRANSPORTATION COMPANY",
    "AMBULATORY CLINIC/CENTER",
    "AMBULATORY SURGICAL CENTER",
    "Art/Recreation Therapist",
    "Athletic Trainer",
    "Audiologist",
    "BIOLOGICAL PRODUCTS MANUFACTURER",
    "BLOOD BANK",
    "Bookkeeper",
    "Business Manager",
    "Business Owner",
    "CHIROPRACTIC GROUP/PRACTICE",
    "Chiropractor",
    "Clinical Nurse Specialist",
    "Clinical Psychologist",
    "Corporate Officer",
    "Counselor, Mental Health",
    "Cytotechnologist",
    "Dental Assistant",
    "DENTAL GROUP/PRACTICE",
    "Dental Hygienist",
    "Dental Resident",
    "selected="">Dentist",
    "Denturist",
    "Dietician",
    "DURABLE MEDICAL EQUIPMENT SUPPLIER",
    "EMT, Basic",
    "EMT, Cardiac/Critical Care",
    "EMT, Intermediate",
    "EMT, Paramedic",
    "END STAGE RENAL DISEASE FACILITY",
    "EYEWEAR EQUIPMENT SUPPLIER",
    "FEDERAL HOSPITAL",
    "FISCAL/BILLING/MANAGEMENT AGENT",
    "GENERAL/ACUTE CARE HOSPITAL",
    "HEALTH CENTER/FEDERALLY QUALIFIED HEALTH CENTER/COMMUNITY HEALTH CENTER",
    "HEALTH INSURANCE COMPANY/PROVIDER",
    "HEALTH MAINTENANCE ORGANIZATION",
    "HOME HEALTH AGENCY/ORGANIZATION",
    "Home Health Aide (Homemaker)",
    "Homeopath",
    "HOSPICE/HOSPICE CARE PROVIDER",
    "Hospital Administrator",
    "Insurance Agent",
    "Insurance Broker",
    "INTERMEDIATE CARE FACILITY FOR MENTALLY RETARDED/SUBSTANCE ABUSE",
    "LABORATORY/CLIA LABORATORY",
    "Licensed Practical or Vocational Nurse",
    "Long-Term Care Administrator",
    "MAMMOGRAPHY SERVICE PROVIDER",
    "Marriage and Family Therapist",
    "Massage Therapist",
    "Medical Assistant",
    "MEDICAL GROUP/PRACTICE",
    "Medical Technologist",
    "MENTAL HEALTH CENTER/COMMUNITY MENTAL HEALTH CENTER",
    "MENTAL HEALTH/SUBSTANCE ABUSE GROUP/PRACTICE",
    "Midwife, Lay (Non-Nurse)",
    "Naturopath",
    "Nuclear Medicine Technologist",
    "Nurse Anesthetist",
    "Nurse Midwife",
    "Nurse Practitioner",
    "Nurses Aide",
    "NURSING FACILITY/SKILLED NURSING FACILITY",
    "NURSING/HEALTH CARE STAFFING SERVICE",
    "Nutritionist",
    "Occupational Therapist",
    "Occupational Therapy Assistant",
    "Ocularist",
    "Optician",
    "OPTICIAN/OPTOMETRIC GROUP/PRACTICE",
    "Optometrist",
    "ORGAN PROCUREMENT ORGANIZATION",
    "Orthotics/Prosthetics Fitter",
    "Osteopathic Physician (DO)",
    "Osteopathic Physician Intern/Resident(DO)",
    "Other Health Care Practitioner - Not Classified",
    "Other Occupation - Not Classified",
    "OTHER TYPE NOT CLASSIFIED - SPECIFY",
    "OUTPATIENT REHABILITATION FACILITY/COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY",
    "Perfusionist",
    "PHARMACEUTICAL MANUFACTURER",
    "Pharmacist",
    "Pharmacist, Nuclear",
    "PHARMACY",
    "Pharmacy Assistant",
    "Pharmacy Intern",
    "Pharmacy Technician",
    "Physical Therapist",
    "Physical Therapy Assistant",
    "PHYSICAL/OCCUPATIONAL THERAPY GROUP/PRACTICE",
    "Physician (MD)",
    "Physician Assistant, Allopathic",
    "Physician Assistant, Osteopathic",
    "Physician Intern/Resident (MD)",
    "Podiatric Assistant",
    "PODIATRIC GROUP/PRACTICE",
    "Podiatrist",
    "PORTABLE X-RAY SUPPLIER",
    "PREFERRED PROVIDER ORGANIZATION",
    "Professional Counselor",
    "Professional Counselor, Alcohol",
    "Professional Counselor, Family/Marriage",
    "Professional Counselor, Substance Abuse ",
    "PROVIDER SPONSORED ORGANIZATION",
    "PSYCHIATRIC HOSPITAL",
    "Psychiatric Technician",
    "PSYCHIATRIC UNIT",
    "Psychological Assistant, Associate, Examiner",
    "Psychologist",
    "PURCHASING SERVICE",
    "Radiation Therapy Technologist",
    "Radiologic Technologist",
    "RADIOLOGY/IMAGING CENTER",
    "Registered (Professional) Nurse",
    "REHABILITATION HOSPITAL",
    "Rehabilitation Therapist",
    "REHABILITATION UNIT",
    "RELIGIOUS, FRATERNAL BENEFIT SOCIETY PLAN",
    "Researcher, Clinical",
    "RESIDENTIAL TREATMENT FACILITY/PROGRAM",
    "Respiratory Therapist",
    "Respiratory Therapy Technician",
    "RURAL HEALTH CLINIC",
    "Salesperson",
    "School Psychologist",
    "Social Worker",
    "Speech/Language Pathologist"
  ]

  private

  def set_provider_attest
    self.provider_attest = ProviderAttest.where(caqh_provider_attest_id: self.caqh_provider_attest_id).last
  end
end
