class ProviderSpecialty < ApplicationRecord
  PRIMARY_KEY_ROW_NAMES = ['ProviderAttestID','ProviderSpecialtyID']

  belongs_to :provider_attest
  has_many :rva_informations, dependent: :destroy

  validates :provider_attest_id, presence: true

  SPECIALITIES = [
    "Adult Cardiac Anesthesiology",
    "Adult Companion",
    "Advanced Practice Midwife",
    "Agencies : Home Health",
    "Air Carrier",
    "Allergy & Immunology",
    "Allergy & Immunology : Clinical & Laboratory Immunology",
    "Allergy & Immunology: Diagnostic Laboratory Immunology",
    "Allergy Immunology, Allergy",
    "Alzheimer Center (Dementia Center)",
    "Ambulance",
    "Ambulance: Air Transport",
    "Ambulance: Land Transport",
    "Ambulance: Water Transport",
    "Ambulatory Health Care Facilities : Clinic/Center : Multi-Specialty",
    "Ambulatory Health Care Facilities : Clinic/Center : Occupational Medicine",
    "American Board of Multiple Specialties in Podiatry ",
    "American Board of Nuclear Cardiology",
    "American Osteopathic Board of Psychiatry & Neurology",
    "Anaplastologist",
    "Anesthesiologist Assistant",
    "Anesthesiology",
    "Anesthesiology : Addiction Medicine",
    "Anesthesiology : Critical Care Medicine",
    "Anesthesiology : Pain Medicine",
    "Anesthesiology: Hospice and Palliative Medicine",
    "Anesthesiology: Pain Management",
    "Anesthesiology: Pediatric Anesthesiology",
    "Art Therapist",
    "Assistant, Behavior Analyst",
    "Assistant, Podiatric",
    "Assisted Living Facility",
    "Assisted Living Facility: Assisted Living, Behavioral Disturbances",
    "Assisted Living Facility: Assisted Living, Mental Illness",
    "Audiologist: Assistive Technology Practitioner",
    "Audiologist: Assistive Technology Supplier",
    "Audiologist-Hearing Aid Fitter",
    "Bariatric Surgery",
    "Behavioral Analyst",
    "Behavioral Health & Social Service Providers : Counselor",
    "Behavioral Health & Social Service Providers : Counselor : Professional",
    "Behavioral Health & Social Service Providers : Marriage & Family Therapist",
    "Behavioral Health & Social Service Providers : Neuropsychologist",
    "Behavioral Health & Social Service Providers : Neuropsychologist : Clinical",
    "Behavioral Health & Social Service Providers : Psychologist",
    "Behavioral Health & Social Service Providers : Social Worker : Clinical",
    "Behaviour Technician",
    "Blood Bank",
    "Board specialty Psychiatry & Neurology:Epilepsy",
    "Bus",
    "Case Management",
    "Case Manager/Care Coordinator",
    "Certified Nurse Midwife",
    "Chiropractic Providers : Chiropractor",
    "Chiropractor: Independent Medical Examiner",
    "Chiropractor: Internist",
    "Chiropractor: Neurology",
    "Chiropractor: Nutrition",
    "Chiropractor: Occupational Health",
    "Chiropractor: Orthopedic",
    "Chiropractor: Pediatric Chiropractor",
    "Chiropractor: Radiology",
    "Chiropractor: Rehabilitation",
    "Chiropractor: Sports Physician",
    "Chiropractor: Thermography",
    "Chore Provider",
    "Christian Science Facility",
    "Christian Science Sanitorium",
    "Chronic Disease Hospital",
    "Chronic Disease Hospital: Children",
    "Clinic/Center",
    "Clinic/Center: Adolescent and Children Mental Health",
    "Clinic/Center: Adult Day Care",
    "Clinic/Center: Adult Mental Health",
    "Clinic/Center: Ambulatory Family Planning Facility",
    "Clinic/Center: Ambulatory Fertility Facility",
    "Clinic/Center: Ambulatory Surgical",
    "Clinic/Center: Amputee",
    "Clinic/Center: Augmentative Communication",
    "Clinic/Center: Birthing",
    "Clinic/Center: Community Health",
    "Clinic/Center: Corporate Health",
    "Clinic/Center: Critical Access Hospital",
    "Clinic/Center: Dental",
    "Clinic/Center: Developmental Disabilities",
    "Clinic/Center: Emergency Care",
    "Clinic/Center: Endoscopy",
    "Clinic/Center: End-Stage Renal Disease (ESRD) Treatment",
    "Clinic/Center: Family Planning, Non-Surgical",
    "Clinic/Center: Federally Qualified Health Center (FQHC)",
    "Clinic/Center: Genetics",
    "Clinic/Center: Health Service",
    "Clinic/Center: Hearing and Speech",
    "Clinic/Center: Infusion Therapy",
    "Clinic/Center: Lithotripsy",
    "Clinic/Center: Magnetic Resonance Imaging (MRI)",
    "Clinic/Center: Medical Specialty",
    "Clinic/Center: Medically Fragile Intants and Children Day Care",
    "Clinic/Center: Mental Health (Including Community Mental Health Center)",
    "Clinic/Center: Methadone Clinic",
    "Clinic/Center: Migrant Health",
    "Clinic/Center: Military Ambulatory Procedure Visits Operational (Transportable)",
    "Clinic/Center: Military and U.S. Coast Guard Ambulatory Procedure",
    "Clinic/Center: Military Outpatient Operational (Transportable) Component",
    "Clinic/Center: Military/U.S. Coast Guard Outpatient",
    "Clinic/Center: Oncology",
    "Clinic/Center: Oncology, Radiation",
    "Clinic/Center: Ophthalmologic Surgery",
    "Clinic/Center: Oral and Maxillofacial Surgery",
    "Clinic/Center: Pain",
    "Clinic/Center: Physical Therapy",
    "Clinic/Center: Podiatric",
    "Clinic/Center: Primary Care",
    "Clinic/Center: Prison Health",
    "Clinic/Center: Public Health, Federal",
    "Clinic/Center: Public Health, State or Local",
    "Clinic/Center: Radiology",
    "Clinic/Center: Radiology, Mammography",
    "Clinic/Center: Radiology, Mobile",
    "Clinic/Center: Radiology, Mobile Mammography",
    "Clinic/Center: Recovery Care",
    "Clinic/Center: Rehabilitation",
    "Clinic/Center: Rehabilitation, Cardiac Facilities",
    "Clinic/Center: Rehabilitation, Comprehensive Outpatient Rehabilitation Facility (CORF)",
    "Clinic/Center: Rehabilitation, Substance Use Disorder",
    "Clinic/Center: Research",
    "Clinic/Center: Rural Health",
    "Clinic/Center: Sleep Disorder Diagnostic",
    "Clinic/Center: Student Health",
    "Clinic/Center: Urgent Care",
    "Clinic/Center: VA",
    "Clinical Ethicist",
    "Clinical Medical Laboratory",
    "Clinical Neuropsychologist",
    "Clinical Neuropsychologist, Clinical",
    "Clinical Nurse Specialist: Acute Care",
    "Clinical Nurse Specialist: Adult Health",
    "Clinical Nurse Specialist: Chronic Care",
    "Clinical Nurse Specialist: Community Health/Public Health",
    "Clinical Nurse Specialist: Critical Care Medicine",
    "Clinical Nurse Specialist: Emergency",
    "Clinical Nurse Specialist: Ethics",
    "Clinical Nurse Specialist: Family Health",
    "Clinical Nurse Specialist: Gerontology",
    "Clinical Nurse Specialist: Holistic",
    "Clinical Nurse Specialist: Home Health",
    "Clinical Nurse Specialist: Informatics",
    "Clinical Nurse Specialist: Long-Term Care",
    "Clinical Nurse Specialist: Medical-Surgical",
    "Clinical Nurse Specialist: Neonatal",
    "Clinical Nurse Specialist: Neuroscience",
    "Clinical Nurse Specialist: Occupational Health",
    "Clinical Nurse Specialist: Oncology",
    "Clinical Nurse Specialist: Oncology, Pediatrics",
    "Clinical Nurse Specialist: Pediatrics",
    "Clinical Nurse Specialist: Perinatal",
    "Clinical Nurse Specialist: Perioperative",
    "Clinical Nurse Specialist: Psych/Mental Health",
    "Clinical Nurse Specialist: Psych/Mental Health, Adult",
    "Clinical Nurse Specialist: Psych/Mental Health, Child & Adolescent",
    "Clinical Nurse Specialist: Psych/Mental Health, Child & Family",
    "Clinical Nurse Specialist: Psych/Mental Health, Chronically Ill",
    "Clinical Nurse Specialist: Psych/Mental Health, Community",
    "Clinical Nurse Specialist: Psych/Mental Health, Geropsychiatric",
    "Clinical Nurse Specialist: Rehabilitation",
    "Clinical Nurse Specialist: School",
    "Clinical Nurse Specialist: Transplantation",
    "Clinical Nurse Specialist: Women's Health",
    "Clinical Pharmacology",
    "Colon & Rectal Surgery",
    "Community Based Residential Treatment Facility, Mental Illness",
    "Community Based Residential Treatment, Mental Retardation and/or Developmental Disabilities",
    "Community Health Worker",
    "Community/Behavioral Health",
    "Complex Family Planning",
    "Contractor",
    "Contractor: Home Modifications",
    "Contractor: Vehicle Modifications",
    "Correctional Medicine",
    "Counselor: Addiction (Substance Use Disorder)",
    "Counselor: Mental Health",
    "Counselor: Pastoral",
    "Counselor: School",
    "Custodial Care Facility",
    "Custodial Care Facility: Adult Care Home",
    "Dance Therapist",
    "Day Training, Developmentally Disabled Services",
    "Day Training/Habilitation Specialist",
    "Dental Assistant",
    "Dental Hygienist",
    "Dental Laboratory",
    "Dental Laboratory Technician",
    "Dental Providers : Dentist",
    "Dental Providers : Dentist : Dental Public Health",
    "Dental Providers : Dentist : Endodontics",
    "Dental Providers : Dentist : Oral and Maxillofacial Pathology",
    "Dental Providers : Dentist : Oral and Maxillofacial Radiology",
    "Dental Providers : Dentist : Orthodontics and Dentofacial Orthopedics",
    "Dental Providers : Dentist : Pediatric Dentistry",
    "Dental Providers : Dentist : Periodontics",
    "Dental Providers : Dentist : Prosthodontics",
    "Dentist, Orofacial Pain",
    "Dentist: General Practice",
    "Dentist: Oral and Maxillofacial Surgery",
    "Denturist",
    "Department of Veterans Affairs (VA) Pharmacy",
    "Dermatology",
    "Dermatology : Clinical & Laboratory Dermatological Immunology",
    "Dermatology : Dermatopathology",
    "Dermatology : MOHS-Micrographic Surgery",
    "Dermatology : Pediatric Dermatology",
    "Dermatology: Dermatological Immunology/Diagnostic and Laboratory Immunology",
    "Dermatology: Micrographic Dermatologic Surgery",
    "Dermatology: Procedural Dermatology",
    "Designation of Focused Practice in Hospital Medicine - Family Medicine Designation",
    "Developmental Therapist",
    "Diagnostic Radiology with Special Competence in Nuclear Radiology - General",
    "Dietary & Nutritional Service Providers : Dietitian, Registered",
    "Dietary Manager",
    "Dietetic Technician, Registered",
    "Dietitian, Registered, Nutrition, Sports Dietetics",
    "Dietitian, Registered: Nutrition, Metabolic",
    "Dietitian, Registered: Nutrition, Pediatric",
    "Dietitian, Registered: Nutrition, Renal",
    "Doula",
    "Driver",
    "Durable Medical Equipment & Medical Supplies",
    "Durable Medical Equipment & Medical Supplies: Customized Equipment",
    "Durable Medical Equipment & Medical Supplies: Dialysis Equipment & Supplies",
    "Durable Medical Equipment & Medical Supplies: Nursing Facility Supplies",
    "Durable Medical Equipment & Medical Supplies: Oxygen Equipment & Supplies",
    "Durable Medical Equipment & Medical Supplies: Parenteral & Enteral Nutrition",
    "Early Intervention Provider Agency",
    "Electrodiagnostic Medicine ",
    "Emergency Medical Technician, Basic",
    "Emergency Medical Technician, Intermediate",
    "Emergency Medical Technician, Paramedic",
    "Emergency Medicine",
    "Emergency Medicine : Emergency Medical Services",
    "Emergency Medicine : Medical Toxicology",
    "Emergency Medicine : Sports Medicine",
    "Emergency Medicine : Undersea and Hyperbaric Medicine",
    "Emergency Medicine: Hospice and Palliative Medicine",
    "Emergency Medicine: Pain Medicine ",
    "Emergency Medicine: Pediatric Emergency Medicine",
    "Emergency Response System Companies",
    "Epilepsy Unit",
    "Exclusive Provider Organization",
    "Eye and Vision Services Providers : Optometrist",
    "Eye Bank",
    "Eyewear Supplier (Equipment, not the service)",
    "Family Medicine",
    "Family Medicine : Addiction Medicine",
    "Family Medicine : Adolescent Medicine",
    "Family Medicine : Geriatric Medicine",
    "Family Medicine : Hospice and Palliative Medicine",
    "Family Medicine : Osteopathic Manipulative Treatment - FP",
    "Family Medicine : Sleep Medicine",
    "Family Medicine : Sports Medicine",
    "Family Medicine: Adult Medicine",
    "Family Medicine: Bariatric Medicine",
    "Family Medicine: Obesity Medicine",
    "Family Medicine: Occupational Medicine",
    "Family Medicine: Occupational Medicine",
    "Family medicine: Pain medicine ",
    "Female Pelvic Medicine and Reconstructive Surgery",
    "Focused Practice in Hospital Medicine - Internal Medicine Designation",
    "Focused Practice in Metabolic Bariatric Surgery - Surgery Designation",
    "Focused Practice in Minimally Invasive Gynecologic Surgery - Obstetrics & Gynecology Designation",
    "Focused Practice in Pediatric and Adolescent Gynecology - Obstetrics & Gynecology Designation",
    "Foster Care Agency",
    "Funeral Director",
    "General Acute Care Hospital",
    "General Acute Care Hospital: Children",
    "General Acute Care Hospital: Critical Access",
    "General Acute Care Hospital: Rural",
    "General Acute Care Hospital: Women",
    "General Practice",
    "General Practice",
    "General Surgery",
    "Genetic Counselor, MS",
    "Group : Multi-Specialty",
    "Health Educator",
    "Health Maintenance Organization",
    "Hearing  Aid Equipment",
    "Hearing Instrument Specialist",
    "Hepatoliary Surgery",
    "Home Delivered Meals",
    "Home Health Aide",
    "Home Infusion",
    "Homemaker",
    "Homeopath",
    "Hospice Care, Community Based",
    "Hospice, Inpatient",
    "Hospitalist",
    "In Home Supportive Care",
    "Independent Medical Examiner",
    "Indian Health Service/Tribal/Urban Indian Health (I/T/U) Pharmacy",
    "Integrative Medicine",
    "Intermediate Care Facility, Mental Illness",
    "Intermediate Care Facility, Mentally Retarded",
    "Internal Medicine",
    "Internal Medicine : Addiction Medicine",
    "Internal Medicine : Adolescent Medicine",
    "Internal Medicine : Advanced Heart Failure & Transplant Cardiology",
    "Internal Medicine : Allergy & Immunology",
    "Internal Medicine : Cardiovascular Disease",
    "Internal Medicine : Clinical Cardiac Electrophysiology",
    "Internal Medicine : Critical Care Medicine",
    "Internal Medicine : Endocrinology",
    "Internal Medicine : Endocrinology, Diabetes & Metabolism",
    "Internal Medicine : Gastroenterology",
    "Internal Medicine : Geriatric Medicine",
    "Internal Medicine : Hematology",
    "Internal Medicine : Hematology & Oncology",
    "Internal Medicine : Hospice and Palliative Medicine",
    "Internal Medicine : Infectious Disease",
    "Internal Medicine : Interventional Cardiology",
    "Internal Medicine : Medical Oncology",
    "Internal Medicine : Nephrology",
    "Internal Medicine : Pulmonary Disease",
    "Internal Medicine : Rheumatology",
    "Internal Medicine : Sleep Medicine",
    "Internal Medicine : Sports Medicine",
    "Internal Medicine : Transplant Hepatology",
    "Internal Medicine, Adult Congenital Heart Disease",
    "Internal Medicine, Neurocritical Care",
    "Internal Medicine: Adult Congenital Hearth Disease",
    "Internal Medicine: Bariatric Medicine",
    "Internal Medicine: Cardiology",
    "Internal Medicine: Clinical & Laboratory Immunology",
    "Internal Medicine: Hepatology",
    "Internal Medicine: Hypertension Specialist",
    "Internal Medicine: Hypertension Specialist",
    "Internal Medicine: Integrative Medicine",
    "Internal Medicine: Magnetic Resonance Imaging (MRI)",
    "Internal medicine: Neocritical care",
    "Internal Medicine: Obesity Medicine",
    "Internal Medicine: Undersea and Hyperbaric Medicine",
    "Interpreter",
    "Interventional Neurology",
    "Interventional Neuroradiology",
    "Interventional Radiology and Diagnostic Radiology",
    "Interventional Radiology and Diagnostic Radiology",
    "Kinesiotherapist",
    "Legal Medicine",
    "Legal Medicine",
    "Licensed Practical Nurse",
    "Licensed Psychiatric Technician",
    "Licensed Vocational Nurse",
    "Local Education Agency (LEA)",
    "Lodging",
    "Long Term Care Hospital",
    "Mastectomy Fitter",
    "Meals",
    "Mechanotherapist",
    "Medical Genetics : Clinical Biochemical Genetics",
    "Medical Genetics : Clinical Cytogenetic",
    "Medical Genetics : Clinical Genetics (M.D.)",
    "Medical Genetics : Clinical Molecular Genetics",
    "Medical Genetics : Molecular Genetic Pathology",
    "Medical Genetics : Ph.D. Medical Genetics",
    "Medical Genetics and Genomics Specialty: Clinical Genetics and Genomics",
    "Medical Genetics, Ph.D. Medical Genetics",
    "Medicare Defined Swing Bed Unit",
    "Micrographic Dermatologic Surgery",
    "Micrographic Dermatologic Surgery",
    "Midwife, Lay",
    "Military Clinical Medical Laboratory",
    "Military Health Care Provider",
    "Military Health Care Provider: Independent Duty Corpsman",
    "Military Health Care Provider: Independent Duty Medical Technicians",
    "Military Hospital",
    "Military Hospital: Community Health",
    "Military Hospital: Military General Acute Care Hospital",
    "Military Hospital: Military General Acute Care Hospital. Operational (Transportable)",
    "Military/U.S. Coast Guard Pharmacy",
    "Military/U.S. Coast Guard Transport",
    "Military/U.S. Coast Guard Transport: Military or U.S. Coast Guard Ambulance, Air Transport",
    "Military/U.S. Coast Guard Transport: Military or U.S. Coast Guard Ambulance, Ground Transport",
    "Military/U.S. Coast Guard Transport: Military or U.S. Coast Guard Ambulance, Water Transport",
    "Minimally Invasive Foot and Ankle Surgery",
    "Music Therapist",
    "Naprapath",
    "Neopathology",
    "NEUROCRITICAL CARE",
    "Neurocritical Care",
    "Neurological Surgery",
    "Neurology",
    "Neuromusculoskeletal Medicine & OMM",
    "Neuromusculoskeletal Medicine, Sports Medicine",
    "Neuromusculoskeletal:Pain Medicine",
    "Neurotology",
    "Non-emergency Medical Transport (VAN)",
    "Non-Pharmacy Dispensing Site",
    "Nuclear Medicine",
    "Nuclear Medicine : In Vivo & In Vitro Nuclear Medicine",
    "Nuclear Medicine : Nuclear Cardiology",
    "Nuclear Medicine : Nuclear Imaging & Therapy",
    "Nurse Practitioner:  Adult Gerontology Acute Care",
    "Nurse Practitioner: Acute Care",
    "Nurse Practitioner: Adult Health",
    "Nurse Practitioner: Community Health",
    "Nurse Practitioner: Critical Care Medicine",
    "Nurse Practitioner: Family",
    "Nurse Practitioner: Gerontology",
    "Nurse Practitioner: Interventional Cardiology",
    "Nurse Practitioner: Neonatal",
    "Nurse Practitioner: Neonatal, Critical Care",
    "Nurse Practitioner: Obstetrics & Gynecology",
    "Nurse Practitioner: Occupational Health",
    "Nurse Practitioner: Pediatrics",
    "Nurse Practitioner: Pediatrics, Critical Care",
    "Nurse Practitioner: Perinatal",
    "Nurse Practitioner: Primary Care",
    "Nurse Practitioner: Psych/Mental Health",
    "Nurse Practitioner: School",
    "Nurse Practitioner: Women's Health",
    "Nurse's Aide",
    "Nursing Care",
    "Nursing Facility/Intermediate Care Facility",
    "Nursing Home Administrator",
    "Nursing Service Providers : Registered Nurse : Psych/Mental Health",
    "Nutritionist",
    "Nutritionist: Nutrition, Education",
    "Obstetrics & Gynecology",
    "Obstetrics & Gynecology : Critical Care Medicine",
    "Obstetrics & Gynecology : Gynecologic Oncology",
    "Obstetrics & Gynecology : Gynecology",
    "Obstetrics & Gynecology : Maternal & Fetal Medicine",
    "Obstetrics & Gynecology : Obstetrics",
    "Obstetrics & Gynecology : Reproductive Endocrinology",
    "Obstetrics & Gynecology : Reproductive Endocrinology and Infertility",
    "Obstetrics & Gynecology : Urogynecology and Reconstructive Pelvic Surgery",
    "Obstetrics & Gynecology: Bariatric Medicine",
    "Obstetrics & Gynecology: Female Pelvic Medicine and Reconstructive Surgery",
    "Obstetrics & Gynecology: Hospice and Palliative Medicine",
    "Obstetrics and Gynecology: Obesity Medicine",
    "Occupational Medicine",
    "Occupational Therapist: Driving and Community Mobility",
    "Occupational Therapist: Environmental Modification",
    "Occupational Therapist: Ergonomics",
    "Occupational Therapist: Feeding, Eating & Swallowing",
    "Occupational Therapist: Gerontology",
    "Occupational Therapist: Hand",
    "Occupational Therapist: Human Factors",
    "Occupational Therapist: Low Vision",
    "Occupational Therapist: Mental Health",
    "Occupational Therapist: Neurorehabilitation",
    "Occupational Therapist: Pediatrics",
    "Occupational Therapist: Physical Rehabilitation",
    "Occupational Therapy Assistant",
    "Occupational Therapy Assistant: Driving and Community Mobility",
    "Occupational Therapy Assistant: Environmental Modification",
    "Occupational Therapy Assistant: Feeding, Eating & Swallowing",
    "Occupational Therapy Assistant: Low Vision",
    "Ophthalmology",
    "Ophthalmology Pediatric Ophthalmology and Strabismus Specialist",
    "Ophthalmology, Neuro-ophthalmology",
    "Ophthalmology, Ophthalmic Plastic and Reconstructive Surgery",
    "Ophthalmology, Pediatric Ophthalmology and Strabismus Specialist",
    "Ophthalmology, Retina Specialist",
    "Ophthalmology, Surgery",
    "Ophthalmology: Glaucoma Specialist ",
    "Ophthalmology: Uveitis and Ocular Inflammatory Disease",
    "Ophthalmology” Cornea and External Diseases Specialist",
    "Opthalmology, Neuro-opthalmology",
    "Opthalmology: Retina Specialist",
    "Optometrist: Corneal and Contact Management",
    "Optometrist: Low Vision Rehabilitation",
    "Optometrist: Occupational Vision",
    "Optometrist: Pediatrics",
    "Optometrist: Sports Vision",
    "Optometrist: Vision Therapy",
    "Oral & Maxillofacial Surgery",
    "Oral Medicinist",
    "Organ Procurement Organization",
    "Orthopaedic Surgery",
    "Orthopaedic Surgery : Hand Surgery",
    "Orthopaedic Surgery : Sports Medicine",
    "Orthopaedic Surgery: Adult Reconstructive Orthopaedic Surgery",
    "Orthopaedic Surgery: Foot and Ankle Surgery",
    "Orthopaedic Surgery: Orthopaedic Sports Medicine",
    "Orthopaedic Surgery: Orthopaedic Surgery of the Spine",
    "Orthopaedic Surgery: Orthopaedic Trauma",
    "Orthopaedic Surgery: Pediatric Orthopaedic Surgery",
    "Orthopedic",
    "Orthopedic Surgery",
    "Orthotist",
    "Other Service Providers : Acupuncturist",
    "Other Service Providers : Midwife, Certified",
    "Other Service Providers : Naturopath",
    "Otolaryn and Facial Plastic Surg",
    "Otolaryngology",
    "Otolaryngology : Facial Plastic Surgery",
    "Otolaryngology : Otolaryngic Allergy",
    "Otolaryngology : Otolaryngology/Facial Plastic Surgery",
    "Otolaryngology : Otology & Neurotology",
    "Otolaryngology : Pediatric Otolaryngology",
    "Otolaryngology : Plastic Surgery within the Head & Neck",
    "Otolaryngology: Head and Neck Surgery",
    "Otolaryngology: Neurotology",
    "Otolaryngology: Sleep Medicine",
    "PACE Provider Organization",
    "Pain Medicine: Interventional Pain Medicine",
    "Pain Medicine: Pain Medicine",
    "Pathology : Anatomic Pathology",
    "Pathology : Anatomic Pathology & Clinical Pathology",
    "Pathology : Anatomic Pathology & Clinical Pathology",
    "Pathology : Blood Banking & Transfusion Medicine",
    "Pathology : Chemical Pathology",
    "Pathology : Clinical Pathology",
    "Pathology : Clinical Pathology/Laboratory Medicine",
    "Pathology : Cytopathology",
    "Pathology : Forensic Pathology",
    "Pathology : Hematology",
    "Pathology : Immunopathology",
    "Pathology : Medical Microbiology",
    "Pathology : Molecular Genetic Pathology",
    "Pathology : Neuropathology",
    "Pathology : Pediatric Pathology",
    "Pathology: Clinical Laboratory Director, Non-physician",
    "Pathology: Dermatopathology",
    "Pathology: Hematopathology",
    "Pediatric Acute Care",
    "Pediatric Ophthalmology and Strabismus Specialist",
    "Pediatric Urology",
    "Pediatrics",
    "Pediatrics : Adolescent Medicine",
    "Pediatrics : Developmental - Behavioral Pediatrics",
    "Pediatrics : Medical Toxicology",
    "Pediatrics : Neonatal-Perinatal Medicine",
    "Pediatrics : Neurodevelopmental Disabilities",
    "Pediatrics : Pediatric Allergy & Immunology",
    "Pediatrics : Pediatric Cardiology",
    "Pediatrics : Pediatric Critical Care Medicine",
    "Pediatrics : Pediatric Emergency Medicine",
    "Pediatrics : Pediatric Endocrinology",
    "Pediatrics : Pediatric Gastroenterology",
    "Pediatrics : Pediatric Hematology-Oncology",
    "Pediatrics : Pediatric Infectious Diseases",
    "Pediatrics : Pediatric Nephrology",
    "Pediatrics : Pediatric Pulmonology",
    "Pediatrics : Pediatric Rheumatology",
    "Pediatrics : Pediatric Transplant Hepatology",
    "Pediatrics : Sports Medicine",
    "Pediatrics, Pediatric Allergy/Immunology",
    "Pediatrics: Adult and Pediatric Allergy and Immunology",
    "Pediatrics: Child Abuse Pediatrics",
    "Pediatrics: Clinical & Laboratory Immunology",
    "Pediatrics: Hospice and Palliative Medicine",
    "Pediatrics: Pediatric Hospital Medicine",
    "Pediatrics: Sleep Medicine ",
    "Pediatrics: Sleep Medicine ",
    "Pedorthist",
    "Perfusionist",
    "Personal Emergency Response Attendant",
    "Pharmacist",
    "Pharmacist, Ambulatory Care",
    "Pharmacist: General Practice",
    "Pharmacist: Geriatric",
    "Pharmacist: Nuclear",
    "Pharmacist: Nutrition Support",
    "Pharmacist: Oncology",
    "Pharmacist: Pediatrics",
    "Pharmacist: Pharmacist Clinician (PhC)/ Clinical Pharmacy Specialist",
    "Pharmacist: Pharmacotherapy",
    "Pharmacist: Psychiatric",
    "Pharmacy",
    "Pharmacy Technician",
    "Pharmacy: Clinic Pharmacy",
    "Pharmacy: Community/Retail Pharmacy",
    "Pharmacy: Compounding Pharmacy",
    "Pharmacy: Home Infusion Therapy Pharmacy",
    "Pharmacy: Institutional Pharmacy",
    "Pharmacy: Long Term Care Pharmacy",
    "Pharmacy: Mail Order Pharmacy",
    "Pharmacy: Managed Care Organization Pharmacy",
    "Pharmacy: Nuclear Pharmacy",
    "Pharmacy: Specialty Pharmacy",
    "Phlebology",
    "Physical Medicine & Rehabilitation",
    "Physical Medicine & Rehabilitation : Brain Injury Medicine",
    "Physical Medicine & Rehabilitation : Neuromuscular Medicine",
    "Physical Medicine & Rehabilitation : Pain Medicine",
    "Physical Medicine & Rehabilitation : Pediatric Rehabilitation Medicine",
    "Physical Medicine & Rehabilitation : Spinal Cord Injury Medicine",
    "Physical Medicine & Rehabilitation : Sports Medicine",
    "Physical Medicine & Rehabilitation: Hospice and Palliative Medicine",
    "Physical Therapist: Cardiopulmonary",
    "Physical Therapist: Electrophysiology, Clinical",
    "Physical Therapist: Ergonomics",
    "Physical Therapist: Geriatrics",
    "Physical Therapist: Hand",
    "Physical Therapist: Human Factors",
    "Physical Therapist: Neurology",
    "Physical Therapist: Orthopedic",
    "Physical Therapist: Pediatrics",
    "Physical Therapist: Sports",
    "Physical Therapy Assistant",
    "Physician Assistant: Medical",
    "Physician Assistant: Surgical",
    "Physician Assistants & Advanced Practice Nursing Providers : Clinical Nurse Specialist",
    "Physician Assistants & Advanced Practice Nursing Providers : Nurse Anesthetist, Certified Registered",
    "Physician Assistants & Advanced Practice Nursing Providers : Nurse Practitioner",
    "Physician Assistants & Advanced Practice Nursing Providers : Physician Assistant",
    "Physiological Laboratory",
    "Plastic and Reconstructive Surgery",
    "Plastic Surgery",
    "Plastic Surgery : Plastic Surgery Within the Head and Neck",
    "Plastic Surgery : Surgery of the Hand",
    "Podiatric Medicine & Surgery Service Providers : Podiatrist",
    "Podiatric Medicine & Surgery Service Providers : Podiatrist : Foot & Ankle Surgery",
    "Podiatric Medicine & Surgery Service Providers : Podiatrist : Foot Surgery",
    "Podiatrist, General Practice",
    "Podiatrist: Limb Preservation and Salvag",
    "Podiatrist: Prevention and Treatment of Diabetic Foot Wounds",
    "Podiatrist: Prevention and Treatment of Diabetic Foot Wounds and Diabetic Footwear",
    "Podiatrist: Primary Podiatric Medicine",
    "Podiatrist: Public Medicine",
    "Podiatrist: Radiology",
    "Podiatrist: Reconstructive Rearfoot/Ankle Surgery",
    "Podiatrist: Sports Medicine",
    "Poetry Therapist",
    "Point of Service",
    "Portable X-Ray Supplier",
    "Preferred Provider Organization",
    "PREVENTION PROFESSIONAL",
    "Preventive Medicine : Aerospace Medicine",
    "Preventive Medicine : Medical Toxicology",
    "Preventive Medicine : Occupational Medicine",
    "Preventive Medicine : Preventive Medicine/Occupational Environmental Medicine",
    "Preventive Medicine : Public Health & General Preventive Medicine",
    "Preventive Medicine : Sports Medicine",
    "Preventive Medicine : Undersea and Hyperbaric Medicine",
    "Preventive Medicine: Addiction Medicine",
    "Preventive Medicine: Clinical Informatics ",
    "Preventive Medicine: Obesity Medicine",
    "Primary Care",
    "Private Vehicle",
    "Proctology",
    "Prosthetic/Orthotic Supplier",
    "Prosthetist",
    "Psychiatric Hospital",
    "Psychiatric Residential Treatment Facility",
    "Psychiatric Unit",
    "Psychiatry & Neurology: Addiction Medicine",
    "Psychiatry & Neurology: Addiction Psychiatry",
    "Psychiatry & Neurology: Bariatric Medicine",
    "Psychiatry & Neurology: Behavioral Neurology & Neuropsychiatry",
    "Psychiatry & Neurology: Brain Injury Medicine",
    "Psychiatry & Neurology: Child & Adolescent Psychiatry",
    "Psychiatry & Neurology: Clinical Neurophysiology",
    "Psychiatry & Neurology: Consultation-Liaison Psychiatry",
    "Psychiatry & Neurology: Diagnostic Neuroimaging",
    "Psychiatry & Neurology: Forensic Psychiatry",
    "Psychiatry & Neurology: Geriatric Psychiatry",
    "Psychiatry & Neurology: Hospice and Palliative Medicine",
    "Psychiatry & Neurology: Neurocritical Care",
    "Psychiatry & Neurology: Neurocritical Care",
    "Psychiatry & Neurology: Neurodevelopmental Disabilities",
    "Psychiatry & Neurology: Neurology",
    "Psychiatry & Neurology: Neurology with Special Qualifications in Child Neurology",
    "Psychiatry & Neurology: Neuromuscular Medicine",
    "Psychiatry & Neurology: Neurophysiology",
    "Psychiatry & Neurology: Neuropsychology",
    "Psychiatry & Neurology: Pain Medicine",
    "Psychiatry & Neurology: Psychiatry",
    "Psychiatry & Neurology: Psychosomatic Medicine",
    "Psychiatry & Neurology: Sleep Medicine",
    "Psychiatry & Neurology: Sports Medicine",
    "Psychiatry & Neurology: Vascular Neurology",
    "Psychiatry and Neurology: Epilepsy",
    "Psychoanalyst",
    "Psychologist: Addiction (Substance Use Disorder)",
    "Psychologist: Adult Development & Aging",
    "Psychologist: Clinical",
    "Psychologist: Clinical Child & Adolescent",
    "Psychologist: Cognitive & Behavioral",
    "Psychologist: Counseling",
    "Psychologist: Educational",
    "Psychologist: Exercise & Sports",
    "Psychologist: Family",
    "Psychologist: Forensic",
    "Psychologist: Group Psychotherapy",
    "Psychologist: Health",
    "Psychologist: Health Service",
    "Psychologist: Men & Masculinity",
    "Psychologist: Mental Retardation & Developmental Disabilities",
    "Psychologist: Prescribing (Medical)",
    "Psychologist: Psychoanalysis",
    "Psychologist: Psychotherapy",
    "Psychologist: Rehabilitation",
    "Psychologist: School",
    "Psychologist: Women",
    "Psychosomatic Medicine",
    "Public Health & General Preventive Medicine",
    "Public Health or Welfare",
    "Pulmonary Function Technologist",
    "Radiologic Technologist",
    "Radiologic Technologist: Bone Densitometry",
    "Radiologic Technologist: Cardiac-Interventional Technology",
    "Radiologic Technologist: Cardiovascular-Interventional Technology",
    "Radiologic Technologist: Computed Tomography",
    "Radiologic Technologist: Magnetic Resonance Imaging",
    "Radiologic Technologist: Mammography",
    "Radiologic Technologist: Nuclear Medicine Technology",
    "Radiologic Technologist: Quality Management",
    "Radiologic Technologist: Radiation Therapy",
    "Radiologic Technologist: Radiography",
    "Radiologic Technologist: Sonography",
    "Radiologic Technologist: Vascular Sonography",
    "Radiologic Technologist: Vascular-Interventional Technology",
    "Radiology",
    "Radiology : Body Imaging",
    "Radiology : Diagnostic Radiology",
    "Radiology : Diagnostic Ultrasound",
    "Radiology : Neuroradiology",
    "Radiology : Nuclear Radiology",
    "Radiology : Pediatric Radiology",
    "Radiology : Radiation Oncology",
    "Radiology : Radiological Physics",
    "Radiology : Therapeutic Radiology",
    "Radiology : Vascular & Interventional Radiology",
    "Radiology Practitioner Assistant",
    "Radiology: Diagnostic Medical Physics",
    "Radiology: Diagnostic Neuroimaging",
    "Radiology: Hospice and Palliative Medicine",
    "Radiology: Interventional Radiology and Diagnostic Radiology",
    "Recreation Therapist",
    "Reflexologist",
    "Registered Nurse",
    "Registered Nurse: Addiction (Substance Use Disorder)",
    "Registered Nurse: Administrator",
    "Registered Nurse: Ambulatory Care",
    "Registered Nurse: Cardiac Rehabilitation",
    "Registered Nurse: Case Management",
    "Registered Nurse: College Health",
    "Registered Nurse: Community Health",
    "Registered Nurse: Continence Care",
    "Registered Nurse: Continuing Education/Staff Development",
    "Registered Nurse: Critical Care Medicine",
    "Registered Nurse: Diabetes Educator",
    "Registered Nurse: Dialysis, Peritoneal",
    "Registered Nurse: Emergency",
    "Registered Nurse: Enterostomal Therapy",
    "Registered Nurse: Flight",
    "Registered Nurse: Gastroenterology",
    "Registered Nurse: General Practice",
    "Registered Nurse: Gerontology",
    "Registered Nurse: Hemodialysis",
    "Registered Nurse: Home Health",
    "Registered Nurse: Hospice",
    "Registered Nurse: Infection Control",
    "Registered Nurse: Infusion Therapy",
    "Registered Nurse: Lactation Consultant",
    "Registered Nurse: Maternal Newborn",
    "Registered Nurse: Medical-Surgical",
    "Registered Nurse: Neonatal Intensive Care",
    "Registered Nurse: Neonatal, Low-Risk",
    "Registered Nurse: Nephrology",
    "Registered Nurse: Neuroscience",
    "Registered Nurse: Nurse Massage Therapist (NMT)",
    "Registered Nurse: Nutrition Support",
    "Registered Nurse: Obstetric, High-Risk",
    "Registered Nurse: Obstetric, Inpatient",
    "Registered Nurse: Occupational Health",
    "Registered Nurse: Oncology",
    "Registered Nurse: Ophthalmic",
    "Registered Nurse: Orthopedic",
    "Registered Nurse: Ostomy Care",
    "Registered Nurse: Otorhinolaryngology & Head-Neck",
    "Registered Nurse: Pain Management",
    "Registered Nurse: Pediatric Oncology",
    "Registered Nurse: Pediatrics",
    "Registered Nurse: Perinatal",
    "Registered Nurse: Plastic Surgery",
    "Registered Nurse: Psych/Mental Health, Adult",
    "Registered Nurse: Psych/Mental Health, Child & Adolescent",
    "Registered Nurse: Registered Nurse First Assistant",
    "Registered Nurse: Rehabilitation",
    "Registered Nurse: Reproductive Endocrinology/Infertility",
    "Registered Nurse: School",
    "Registered Nurse: Urology",
    "Registered Nurse: Women's Health Care, Ambulatory",
    "Registered Nurse: Wound Care",
    "Rehabilitation Counselor",
    "Rehabilitation Counselor: Assistive Technology Practitioner",
    "Rehabilitation Counselor: Assistive Technology Supplier",
    "Rehabilitation Counselor: Orientation and Mobility Training Provider",
    "Rehabilitation Hospital",
    "Rehabilitation Hospital: Children",
    "Rehabilitation Practitioner",
    "Rehabilitation Unit",
    "Rehabilitation, Substance Use Disorder Unit",
    "Religious Nonmedical Health Care Institution",
    "Religious Nonmedical Nursing Personnel",
    "Religious Nonmedical Practitioner",
    "Reproductive Endocrinology and Infertility ",
    "Residential Treatment Facility, Emotionally Disturbed Children",
    "Residential Treatment Facility, Mental Retardation and/or Developmental Disabilities",
    "Residential Treatment Facility, Physical Disabilities",
    "Respiratory Therapist, Certified: Critical Care",
    "Respiratory Therapist, Certified: Educational",
    "Respiratory Therapist, Certified: Emergency Care",
    "Respiratory Therapist, Certified: General Care",
    "Respiratory Therapist, Certified: Geriatric Care",
    "Respiratory Therapist, Certified: Home Health",
    "Respiratory Therapist, Certified: Neonatal/Pediatrics",
    "Respiratory Therapist, Certified: Palliative/Hospice",
    "Respiratory Therapist, Certified: Patient Transport",
    "Respiratory Therapist, Certified: Pulmonary Diagnostics",
    "Respiratory Therapist, Certified: Pulmonary Function Technologist",
    "Respiratory Therapist, Certified: Pulmonary Rehabilitation",
    "Respiratory Therapist, Certified: SNF/Subacute Care",
    "Respiratory Therapist, Registered",
    "Respiratory Therapist, Registered: Critical Care",
    "Respiratory Therapist, Registered: Educational",
    "Respiratory Therapist, Registered: Emergency Care",
    "Respiratory Therapist, Registered: General Care",
    "Respiratory Therapist, Registered: Geriatric Care",
    "Respiratory Therapist, Registered: Home Health",
    "Respiratory Therapist, Registered: Neonatal/Pediatrics",
    "Respiratory Therapist, Registered: Palliative/Hospice",
    "Respiratory Therapist, Registered: Patient Transport",
    "Respiratory Therapist, Registered: Pulmonary Diagnostics",
    "Respiratory Therapist, Registered: Pulmonary Function Technologist",
    "Respiratory Therapist, Registered: Pulmonary Rehabilitation",
    "Respiratory Therapist, Registered: SNF/Subacute Care",
    "Respiratory, Rehabilitative & Restorative Service Providers : Massage Therapist",
    "Respiratory, Rehabilitative & Restorative Service Providers : Occupational Therapist",
    "Respiratory, Rehabilitative & Restorative Service Providers : Orthotics/Prosthetics Fitter",
    "Respiratory, Rehabilitative & Restorative Service Providers : Physical Therapist",
    "Respiratory, Rehabilitative & Restorative Service Providers : Respiratory Therapist, Certified",
    "Respite Care",
    "Respite Care: Respite Care Camp",
    "Respite Care: Respite Care, Mental Illness, Child",
    "Respite Care: Respite Care, Mental Retardation and/or Developmental Disabilities, Child",
    "Respite Care: Respite Care, Physical Disabilities, Child",
    "Secured Medical Transport (VAN)",
    "Single Specialty",
    "Skilled Nursing Facility",
    "Skilled Nursing Facility: Nursing Care, Pediatric",
    "Sleep Medicine",
    "Sleep Medicine",
    "Sleep Specialist, PhD",
    "Social Worker",
    "Social Worker: School",
    "Spec/Tech, Cardiovascular",
    "Spec/Tech, Cardiovascular: Cardiovascular Invasive Specialist",
    "Spec/Tech, Cardiovascular: Sonography",
    "Spec/Tech, Cardiovascular: Vascular Specialist",
    "Spec/Tech, Health Info",
    "Spec/Tech, Health Info: Coding Specialist, Hospital Based",
    "Spec/Tech, Health Info: Coding Specialist, Physician Office Based",
    "Spec/Tech, Health Info: Registered Record Administrator",
    "Spec/Tech, Pathology",
    "Spec/Tech, Pathology: Blood Banking",
    "Spec/Tech, Pathology: Chemistry",
    "Spec/Tech, Pathology: Cytotechnology",
    "Spec/Tech, Pathology: Hemapheresis Practitioner",
    "Spec/Tech, Pathology: Hematology",
    "Spec/Tech, Pathology: Histology",
    "Spec/Tech, Pathology: Immunology",
    "Spec/Tech, Pathology: Laboratory Management",
    "Spec/Tech, Pathology: Laboratory Management, Diplomate",
    "Spec/Tech, Pathology: Medical Technologist",
    "Spec/Tech, Pathology: Microbiology",
    "Special Hospital",
    "Specialist",
    "Specialist/Technologist",
    "Specialist/Technologist",
    "Specialist/Technologist, Other",
    "Specialist/Technologist, Other: Art, Medical",
    "Specialist/Technologist, Other: Biochemist",
    "Specialist/Technologist, Other: Biomedical Engineering",
    "Specialist/Technologist, Other: Biomedical Photographer",
    "Specialist/Technologist, Other: Biostatistician",
    "Specialist/Technologist, Other: Certified First Assistant",
    "Specialist/Technologist, Other: EEG",
    "Specialist/Technologist, Other: Electroneurodiagnostic",
    "Specialist/Technologist, Other: Geneticist, Medical (PhD)",
    "Specialist/Technologist, Other: Graphics Methods",
    "Specialist/Technologist, Other: Illustration, Medical",
    "Specialist/Technologist, Other: Nephrology",
    "Specialist/Technologist: Athletic Trainer",
    "Specialist/Technologist: Audiology Assistant",
    "Specialist/Technologist: Rehabilitation, Blind",
    "Specialist/Technologist: Speech-Language Assistant",
    "Specialist: Graphics Designer",
    "Specialist: Prosthetics Case Management",
    "Specialist: Research Data Abstracter/Coder",
    "Specialist: Research Study",
    "Speech, Language and Hearing Service Providers : Audiologist",
    "Speech-Language Pathologist",
    "Sports Medicine",
    "Student in an Organized Health Care Education/Training Program",
    "Substance Abuse Rehabilitation Facility",
    "Substance Abuse Rehabilitation Facility: Substance Abuse Treatment, Children",
    "Supplier",
    "Supports Brokerage",
    "Surgery",
    "Surgery : Pediatric Surgery",
    "Surgery : Plastic and Reconstructive Surgery",
    "Surgery : Surgery of the Hand",
    "Surgery : Surgical Critical Care",
    "Surgery : Surgical Oncology",
    "Surgery : Vascular Surgery",
    "Surgery: Addiction Medicine ",
    "Surgery: Complex General Surgical Oncology",
    "Surgery: Hospice and Palliative Medicine",
    "Surgery: Trauma Surgery",
    "Taxi",
    "Technician",
    "Technician, Cardiology",
    "Technician, Health Information",
    "Technician, Health Information: Assistant Record Technician",
    "Technician, Other",
    "Technician, Other: Biomedical Engineering",
    "Technician, Other: Darkroom",
    "Technician, Other: EEG",
    "Technician, Other: Renal Dialysis",
    "Technician, Other: Veterinary",
    "Technician, Pathology",
    "Technician, Pathology: Histology",
    "Technician, Pathology: Medical Laboratory",
    "Technician, Pathology: Phlebotomy",
    "Technician/Technologist",
    "Technician/Technologist: Contact Lens",
    "Technician/Technologist: Contact Lens Fitter",
    "Technician/Technologist: Ocularist",
    "Technician/Technologist: Ophthalmic",
    "Technician/Technologist: Ophthalmic Assistant",
    "Technician/Technologist: Optician",
    "Technician/Technologist: Optometric Assistant",
    "Technician/Technologist: Optometric Technician",
    "Technician/Technologist: Orthoptist",
    "Technician: Attendant Care Provider",
    "Technician: Personal Care Attendant",
    "Technologists, Technicians & Other Technical Service Providers : Specialist/Technologist, Other : Surgical",
    "Therapeutic Medical Physics",
    "Therapeutic Radiology",
    "Thoracic and Cardiac Surgery",
    "Thoracic and Cardiac Surgery: Congenital Cardiac Surgery",
    "Thoracic Surgery (Cardiothoracic Vascular Surgery)",
    "Thoriaric Surgery",
    "Train",
    "Transplant Surgery",
    "Transportation Broker",
    "Urological Surgery ",
    "Urology",
    "Urology: Female Pelvic Medicine and Reconstructive Surgery",
    "Urology: Pediatric Urology’",
    "Urology: Urogynecology and Reconstructive Pelvic Surgery",
    "Veterinarian",
    "Veterinarian: Medical Research",
  ]

  ISSUING_BOARD = [
    "American Board of Addiction Medicine",
    "American Board of Allergy Immunology",
    "American Board of Ambulatory Foot Surgery",
    "American Board of Anesthesiology",
    "American Board of Clinical Neuropsychology",
    "American Board of Colon Rectal Surgery",
    "American Board of Dental Public Health",
    "American Board of Dermatology",
    "American Board of Dermatopathology",
    "American Board of Emergency Medicine",
    "American Board of Endodontics",
    "American Board of Family Medicine",
    "American Board of Foot and Ankle Surgery",
    "American Board of Genetics Counseling Inc",
    "American Board of Internal Medicine",
    "American Board of Lower Extremity Surgery ",
    "American Board of Medical Genetics",
    "American Board of Medical Genetics and Genomics",
    "American Board of Multiple Specialists in Podiatry",
    "American Board of Multiple Specialties in Podiatry",
    "American Board of Neurological Surgery",
    "American Board of Nuclear Cardiology",
    "American Board of Nuclear Medicine",
    "American Board of Obesity Medicine",
    "American Board of Obstetrics Gynecology",
    "American Board of Ophthalmology",
    "American Board of Oral Maxillofacial Pathology",
    "American Board of Oral Maxillofacial Radiology",
    "American Board of Oral and Maxillofacial Surgery",
    "American Board of Orthodontics",
    "American Board of Orthopaedic Surgery",
    "American Board of Orthopedic Surgery",
    "American Board of Otolaryngology",
    "American Board of Otolaryngology - Head and Neck Surgery",
    "American Board of Pain Medicine",
    "American Board of Pathology",
    "American Board of Pediatric Dentistry",
    "American Board of Pediatrics",
    "American Board of Periodontology",
    "American Board of Phlebology",
    "American Board of Physical Medicine Rehabilitation",
    "American Board of Physical Therapy Specialties",
    "American Board of Physician Specialties",
    "American Board of Plastic Surgery",
    "American Board of Podiatric Medicine",
    "American Board of Podiatric Orthopedic and Primary Podiatric Medicine",
    "American Board of Podiatric Surgery",
    "American Board of Preventive Medicine ",
    "American Board of Prosthodontics",
    "American Board of Psychiatry Neurology",
    "American Board of Radiology",
    "American Board of Sleep Medicine",
    "American Board of Surgery",
    "American Board of Thoracic Surgery",
    "American Board of Urology",
    "American Board of Vascular Medicine",
    "American Board of Venous and Lymphatic Medicine",
    "American Dental Board of Anesthesiology",
    "American Osteopathic Board of Anesthesiology",
    "American Osteopathic Board of Dermatology",
    "American Osteopathic Board of Emergency Medicine",
    "American Osteopathic Board of Family Physicians",
    "American Osteopathic Board of Family Practice",
    "American Osteopathic Board of General Medicine",
    "American Osteopathic Board of Internal Medicine",
    "American Osteopathic Board of Neurological Surgery",
    "American Osteopathic Board of Neurology and Psychiatry",
    "American Osteopathic Board of Neuromusculoskeletal Medicine",
    "American Osteopathic Board of Nuclear Medicine",
    "American Osteopathic Board of Obstetrics and Gynecology",
    "American Osteopathic Board of Ophthalmology ",
    "American Osteopathic Board of Ophthalmology and Otolaryngology",
    "American Osteopathic Board of Orthopedic Surgery",
    "American Osteopathic Board of Otolaryn and Facial Plastic Surg",
    "American Osteopathic Board of Otolaryngology",
    "American Osteopathic Board of Pathology",
    "American Osteopathic Board of Pediatrics",
    "American Osteopathic Board of Physical and Rehabil",
    "American Osteopathic Board of Physical Medicine Rehabilitation",
    "American Osteopathic Board of Plastic and Reconstructive Surgery",
    "American Osteopathic Board of Preventive Medicine",
    "American Osteopathic Board of Proctology",
    "American Osteopathic Board of Radiology",
    "American Osteopathic Board of Surgery",
    "American Osteopathic Board of Urological Surgery",
    "ASHA",
    "Family Medicine",
    "Family Medicine: Pain Medicine",
    "Integrative Medicine",
    "National Board for Certified Counselors",
    "National Board of Certification and Recertificatio",
    "National Board of Osteopathic Medical Examiners",
    "National Board of Physicians and Surgeons",
    "Neurocritical Care",
    "Other, not listed",
    "Pain Medicine"
  ]
end
