class ProviderPersonalAttempt < ApplicationRecord
  belongs_to :provider_attest

  ATTEMPT_STATUS = [
    "3/7/2016",
    "AM",
    "BADN",
    "BLOC",
    "Bounced",
    "BUSY",
    "Call rejected",
    "Cancelled",
    "DDCC",
    "Deceased",
    "DEDR",
    "DEDU",
    "Delegated",
    "DESCEASED",
    "DISC",
    "DISC PARTICIPATION",
    "Disconnected",
    "Discontinued Participation",
    "DISCONTINUED PARTICPATION",
    "DiscontinuedParticipation",
    "Discontinuing Participation",
    "DNCL",
    "Docs Received",
    "ERR",
    "Error",
    "Fax Number",
    "ForReview",
    "ICPT",
    "INCOMING",
    "Invalid or incorrectly formatted number",
    "LA",
    "left vm advising provider recred app is due complete on PS and attest cb 8559786115",
    "line busy",
    "LiveAnswer",
    "NO ANSWER",
    "NOAN",
    "NOANSWER",
    "NOFN",
    "NOT AT LOCATION",
    "NOTATLOCATION",
    "Number unallocated disconnected or not in service",
    "Number unallocated, disconnected or not in service",
    "Number unallocated, disconnected, or not in service",
    "OOUT",
    "Opened",
    "Out of Network",
    "Processing",
    "PVOC",
    "Relocated Out of State",
    "Researched",
    "Retired",
    "Sent",
    "Suppressed",
    "Terminated",
    "TFDD",
    "TMDD",
    "Undeliverable",
    "VOIC",
    "Wrong Number",
  ]

  CONTACT_METHOD = [
    "Application Review",
    "BCPhone",
    "Document load",
    "E-mail",
    "Email",
    "Fax",
    "Fax and Mail",
    "LA",
    "Mail",
    "Phone",
    "Website",
  ]
end
