class StaffSpokenForeignLanguage < ApplicationRecord
  belongs_to :practice_information

  LANGUAGE = 
  [
    "& gujarati",
    "& Hindi",
    "& Punjabi",
    "& Spanish",
    "& TAGALOG",
    "'')lish",
    "457",
    "538",
    "a hygienist speaks Polish",
    "a language interpreting service",
    "Abkhazian",
    "access to language bank",
    "Aerobic",
    "Afan (Oromo)",
    "Afar",
    "Afghani (Pashto)",
    "Afrikaans",
    "Albanian",
    "all",
    "All (We are contracted with another company that interprets any languages)",
    "All (We contract with a company that can interpret any language)",
    "all as needed",
    "All languages",
    "All languages and sign language",
    "all languages are available",
    "All Languages are interpretable",
    "all languages translated through our language line (by phone)",
    "All others can be with advance notice",
    "All the above",
    "All -Translation Service",
    "All types",
    "All-Interpreting Service",
    "All-Translation Service",
    "Alsatian",
    "Also have access to language line.",
    "also we have an account with Certified Languages International",
    "also.",
    "American English",
    "American Sign Language",
    "American Sign Language (Speak Fluent)",
    "American Sign Language Read Fluent)",
    "Amhari",
    "Amharic",
    "and Armenian",
    "and English",
    "and French",
    "and Korean",
    "and Vietnamese",
    "any language",
    "any language as needed",
    "any languages needed",
    "any major language available telephonically",
    "Apanish",
    "ARAB",
    "ARABIB",
    "Arabic",
    "Arabic & Spanish",
    "Arabic English",
    "Arabic.English",
    "ARABIC-ENGLISH",
    "aramaic",
    "Aramiac",
    "Armanian",
    "armenain",
    "Armenian",
    "Armenian and Arabic",
    "armenian tagalog spanish farsi",
    "Armenina",
    "Armenn",
    "arrangement made as neccesary",
    "arrangements made as needed",
    "As needed",
    "ASL",
    "ASL - via videoconference",
    "Assamese",
    "Assyrian",
    "Assyrian & Arabic",
    "Assyrian & Arabic",
    "Assyrian Neo-Aramaic",
    "Asyrian",
    "AT&T Interpretation Service",
    "AT&T Intrepretation Services",
    "ATT Conference Assistance",
    "Available with prior arrangements.",
    "Azari",
    "Azerbaijani",
    "Bashkir",
    "Basic Hebrew",
    "BASIC HEWBREW",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bengali; Hindi",
    "Bengali;Bangla",
    "Bengali;Hindi",
    "Bermese",
    "Bhojpuri",
    "Bhutani",
    "Bicol",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Brazilian Portuguese",
    "Breton",
    "Bularian",
    "Bulgarian",
    "Bulgarian English",
    "Burmese",
    "Burmrse",
    "but not for therapy",
    "by contract basis",
    "By phone app",
    "by request",
    "By the staff",
    "By the staff; Spanish",
    "Byelorussian",
    "Cambodian",
    "can be acqired as necessary",
    "cantoneese",
    "Cantones",
    "Cantonese",
    "Cantonese Chinese",
    "cantoneses",
    "Cantonesse",
    "Cantonse",
    "Cape Verde Creole",
    "Cape Verdean Creole",
    "Catalan",
    "Cebuano",
    "Chaldean",
    "Chiense",
    "CHINES",
    "Chinese",
    "Chinese ( Cantonese)",
    "Chinese ( Mandarin)",
    "Chinese (Cantonese)",
    "Chinese (Mandarin)",
    "chinese mandarin",
    "Chinese- Mandarin",
    "chinese spanish",
    "Chinese/Mandarin",
    "Chinese-Mandarin",
    "Chiu Chow",
    "contract",
    "contract with interpreter service....over 200 languages available",
    "contract with interpreter service...over 200 languages available",
    "Contracted with language line",
    "conversational Portuguese",
    "Conversational Punjabi",
    "Conversational Spanish",
    "Corsican",
    "could also use our language line",
    "creiole",
    "creol",
    "Creole",
    "Cristina",
    "Croacian",
    "croasian",
    "Croatian",
    "czec",
    "Czech",
    "Danish",
    "Deaf",
    "Dutch",
    "e",
    "Eastern Aramaic",
    "Eglish",
    "Egyptian",
    "Engiish/Spanish",
    "Engish",
    "Engjavascript:__doPostBack('ctl00$mainContent$UniversalApplication$PracticeLocation$AccordionPane5_header$LinkButton5'",
    "Engli",
    "Engliah",
    "ENGLICH",
    "ENGLIGH",
    "Englilsh",
    "Englis",
    "English",
    "English",
    "English - Spanish",
    "English hindiindian",
    "English - Interpreters avail",
    "English Korean",
    "English - Spanish",
    "English Spanish Tagalog",
    "English Vietnamese",
    "English & Hindi",
    "English & Spanish",
    "English also a hygienist that speaks Polish",
    "English and Spanish",
    "English and American Sign Language",
    "English and Arabic",
    "English and chinese",
    "English and French",
    "English and Hindi",
    "English and Korean",
    "English and Spanish",
    "English and the Doctor speaks Spanish",
    "English and Urdo",
    "English ARABIC SPANISH",
    "English Bengali",
    "English Cambodian Frenc",
    "English Cambodian French",
    "English Farsi",
    "English- Farsi",
    "English- farsi-spanish",
    "English Greek Spanish Filipino",
    "english hebrew",
    "English Hindi",
    "English Hindi Telugu",
    "English hindiindian",
    "English Italian",
    "English lithuanian Russian",
    "English only",
    "English Punjabi Hindi",
    "English Romanian Hebrew",
    "English Romanian Hebrew Russian Polish Spanish",
    "English Russian",
    "English Russian Spanish",
    "English Russian Spanish",
    "English RUSSION SPANISH CHINESE",
    "English sign language",
    "english spanish",
    "English- Spanish",
    "English Spanish and Russian",
    "English SPANISH ARABIC",
    "English Spanish French",
    "English spanish polish",
    "English Spanish Punjabi Hindi Gujarati",
    "English Spanish TAgalog",
    "English SPANISH TAMIL",
    "English tagala Chinese",
    "English Tagalog",
    "English TAMIL",
    "English vietnamese",
    "English. Icelandic",
    "English.Spanish",
    "English/Spanish",
    "English/spanish/chinise/hindi/tamil",
    "English;",
    "ENGLISH; HINDI; PUNJABI",
    "english; russian",
    "English; Spanish; Vietnamese",
    "English-Farsi",
    "English-farsi-spanish",
    "Englishs",
    "EnglishSpanish",
    "English-Spanish",
    "englsih",
    "enhlish hindi",
    "enlgish",
    "Enlish",
    "Eriteria",
    "Espanol",
    "ESPANOL- ENGLISH",
    "ESPANOL-ENGLISH",
    "Esperanto",
    "Estonian",
    "Ethiopian",
    "facry",
    "Fanti",
    "farcey",
    "Farci",
    "Faroese",
    "FARSHI",
    "Farsi",
    "Farsi (Persian)",
    "Farsi and Spanish",
    "farsis",
    "farzi",
    "fasi",
    "Fiji",
    "Filiino",
    "Filipino",
    "Filipino (Tagalog)",
    "Finnish",
    "Flemish",
    "Fookienese",
    "Forci",
    "Forci and Progusese",
    "French",
    "French - adequate for intake",
    "French and Arabic",
    "French and Spanich",
    "French Creole",
    "French ENGLISH Spanish",
    "French German",
    "French Haitian Creole",
    "french Spanish Creole",
    "French. Spanish",
    "French-creole",
    "Frisian",
    "Galican",
    "Galician",
    "Georgian",
    "ger",
    "germ",
    "German",
    "German English",
    "German Portugeese",
    "Germany",
    "Ghafoori",
    "google interpretion",
    "Greek",
    "Greenlandic",
    "Guamainan",
    "Guarani",
    "Gujarathi",
    "Gujarati",
    "gujarati and urdu",
    "Gujarti",
    "Gujarti/ Hindi",
    "gujrathi",
    "gujrati",
    "Gujuarti",
    "Gujurati",
    "Gurjarati",
    "Haitian",
    "Haitian Creole",
    "Haitian-creole",
    "Hatian Creole",
    "Hausa",
    "hawaiian",
    "he",
    "hebreo",
    "Hebrew",
    "hebrew english",
    "hebrew yiddish english",
    "herbrew",
    "Hind Spanish",
    "hindhi",
    "Hindi",
    "hindi punjabi urdu spanish",
    "Hindi & Punjabi",
    "Hindi & Urdu",
    "Hindi & Urud",
    "hindi and gujarati",
    "hindi and punjabi",
    "Hindi English",
    "Hindi gujarati",
    "hindi spanish",
    "hindi tamil",
    "Hindi Telugu",
    "Hindi. Punjabi",
    "Hindi/Urdu",
    "HINDI; PUNJABI",
    "hindu",
    "Hindy",
    "Hispanic",
    "Hkmer",
    "Hmong",
    "hokkian",
    "Hospital translation services",
    "hun",
    "Hungarian",
    "I have no staff",
    "Ibo",
    "Icelandic",
    "Igbo",
    "Igboh",
    "ilocano",
    "india",
    "Indian",
    "Indonesia",
    "Indonesian",
    "Indonesian English",
    "Interlingua",
    "Interlingue",
    "Interpreter Line",
    "Interpreter Services",
    "Interpreter Services Available as Needed",
    "Interpreter Services available for many languages",
    "Interpreter upon request",
    "interpreters",
    "Interpreters are available as necessary and set up on an as needed basis",
    "Interpreters are required",
    "Interpreters are required at all locations",
    "Interpreters avaialable upon request",
    "Interpreters available",
    "Interpreters available upon request",
    "Interpreters provided upon request",
    "Interpreters used as needed",
    "interpretors",
    "Inuktitut",
    "Inupiak",
    "Irabic",
    "Iran",
    "Iranian",
    "Irish",
    "Italian",
    "Jamaican",
    "Jap",
    "Japanese",
    "Japanese & English",
    "Japaneses",
    "Japannese",
    "Japenese",
    "Japense",
    "Javanese",
    "Kambodian",
    "KANADA",
    "Kannada",
    "Karen",
    "Karenni",
    "Kashmiri",
    "Kazakh",
    "Khemer",
    "khmer",
    "Khmer/Cambodian",
    "kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Kiswahili",
    "Koean",
    "Konkani",
    "korea",
    "Korean",
    "korean and spanish",
    "korean English",
    "Korean Spanish",
    "Korean Spanish English",
    "KOREN",
    "korena",
    "Koreran",
    "Kreyol'",
    "Kurdish",
    "Kurundi",
    "Lancano",
    "Language",
    "language bank",
    "LANGUAGE LINE",
    "Language Line available",
    "Language Line Interpretors",
    "Language line is utilized",
    "Lannder",
    "Lao",
    "Laothian",
    "Laotian",
    "Latin",
    "Latvian",
    "Latvian;Lettish",
    "Laus",
    "Lebanese",
    "Limited Hindi",
    "limited spanish",
    "Lingala",
    "Lithuania",
    "Lithuanian",
    "Lithuanian Russian",
    "little spanish",
    "Llancano",
    "Luo",
    "Lupe",
    "Macedonian",
    "Madarin",
    "Maithili",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Malaylam",
    "Malaysian",
    "Maltese",
    "manadarin",
    "Mandarian",
    "mandarim",
    "Mandarin",
    "Mandarin and Spanish",
    "Mandarin Chinese",
    "Manderin",
    "Manderin chinese",
    "Manderine",
    "Mandrin",
    "manrain",
    "many others",
    "Maori",
    "Marathi",
    "medical Spanish",
    "Mien",
    "minimal spanish",
    "Mirathi",
    "Moldavian",
    "Mong",
    "Mongolian",
    "Montenegrian",
    "more than 200 languages supported",
    "Morrrocan",
    "multi language line",
    "multiple language interpreters through hospital",
    "Multiple language translation available",
    "Multiple languages avail through interpreters English",
    "Multiple languages available",
    "Multiple languages interpreted",
    "N/A",
    "na",
    "Native American Dialect",
    "Nauru",
    "Navajo",
    "Navijo",
    "Nepali",
    "New England Interpreter Services",
    "Newari",
    "no",
    "No foreign languages spoken",
    "No foreign languages writen",
    "No foreign languages written",
    "non",
    "none",
    "NonStandard English of the West Indies",
    "Norwegian",
    "Not applicable",
    "not therapeutically)",
    "Occitan",
    "on as needed basis",
    "On request",
    "on staff",
    "Only on Wednesdays",
    "Ordu",
    "Oriya",
    "Other",
    "Other (Specify)",
    "other languages as needed",
    "other languages can be translated through our language line (phone)",
    "other languages can be translated via language line (phone)",
    "other we have interpreters",
    "other- We have interpreters as well",
    "Other- We have interpreters to all languages",
    "Over 100",
    "Over 100 Available",
    "Pakistan",
    "pakistani",
    "Parsian",
    "Pashto",
    "Pashto;Pushto",
    "Pashtu",
    "Perisan farsi",
    "Persian",
    "Persian (Farsi)",
    "Persian (Farsi) and spanish",
    "Persian(Farsi)",
    "philipino",
    "Philippino",
    "phillipino",
    "phone service can be used.",
    "please call",
    "please contact",
    "Pohnpeian",
    "pol",
    "Polish",
    "Polish English",
    "Polsih",
    "Portguese",
    "Portugeese",
    "portugese",
    "Portugu",
    "portugues",
    "Portuguese",
    "Portuguese and Spanish",
    "Portuguese Creole",
    "Portuguese English",
    "Portuguese Spanish",
    "Portuguse",
    "Pothohari",
    "potuguese",
    "Progusese",
    "Protugese",
    "PUBJABI",
    "Pujabi",
    "pun",
    "Punajbi",
    "Punjabi",
    "Punjabi & Arabic",
    "Punjabi & Hindi",
    "Punjabi & Spanish",
    "punjabi urdu to english",
    "PUSHTO",
    "Quechua",
    "Remedial",
    "Rhaeto-Romance",
    "romaina",
    "romainan",
    "ROMAINIAN",
    "Romanian",
    "Rusian",
    "Russain",
    "Russan",
    "Russia",
    "Russian",
    "Russian and american sign language",
    "Russian and english",
    "russian and spanish",
    "Russian English",
    "Russin",
    "Russina",
    "RUSSION",
    "S",
    "Samaoan",
    "Samoan",
    "Sangho",
    "Sanish",
    "Sanskrit",
    "Sapanish",
    "Sapnish",
    "Scot Gaelic",
    "Serbian",
    "Serbo- Croatian",
    "Serbo-Croatian",
    "Sesotho",
    "Setswana",
    "Shona",
    "Sign",
    "Sign Language",
    "Sign Language American",
    "Sign Language Tactile",
    "Sindhi",
    "Singhalese",
    "Single",
    "Sinhalese",
    "Siswati",
    "Slovak",
    "Slovakian",
    "Slovenian",
    "Soanish",
    "Somali",
    "Somalia",
    "Some American Sign Language",
    "some French",
    "some Italian & French",
    "some spanish",
    "some Spanish and Japanese",
    "some speak Spanish",
    "sp",
    "spa",
    "Spainish",
    "spainsh",
    "spaish",
    "span",
    "spangish",
    "spani",
    "Spanich",
    "Spanihs",
    "Spanis",
    "spanisg",
    "Spanish",
    "Spanish German",
    "spanish & english",
    "Spanish & Lithuanian",
    "Spanish (available by phone contract)",
    "Spanish (conversational)",
    "SPANISH (DOCTOR ONLY)",
    "SPANISH (DR. ONLY)",
    "Spanish (minimal-to-moderate)",
    "Spanish (myself only - poor-to-fair)",
    "Spanish (very basic knowledge)",
    "Spanish (very very basic)",
    "SPANISH / TAGLOG",
    "SPANISH /TAGLOG",
    "Spanish 60%",
    "spanish afrikaans",
    "Spanish and creole",
    "spanish and English",
    "Spanish and farsi",
    "Spanish and French",
    "Spanish and multiple other languages",
    "spanish and polish",
    "Spanish and Portuguese",
    "SPANISH AND SOME FRENCH",
    "Spanish and Vietnamese",
    "Spanish by phone",
    "Spanish Dr only",
    "Spanish English",
    "Spanish- English",
    "Spanish fairly well for one on one",
    "spanish farsi",
    "Spanish French Korean",
    "Spanish interpreters",
    "Spanish Korean",
    "Spanish Korean Engish",
    "SPANISH RUSSION CHINESE",
    "SPANISH TAGALA",
    "Spanish Tagala Chinese",
    "Spanish Tagalog",
    "SPANISH TAMIL HINDI",
    "Spanish Vietnamese",
    "Spanish w prior arrangements",
    "Spanish w/ prior arrangements",
    "Spanish(limited)",
    "spanish(little) vietnamese",
    "Spanish.",
    "Spanish. English",
    "Spanish. Russian",
    "Spanish.German",
    "Spanish; by the office staff",
    "Spanish; by the staff",
    "Spanisha",
    "SPANSH",
    "Spansih",
    "spansish",
    "SPASNISH",
    "SPENISH",
    "Spnish",
    "Spsnish",
    "Sundanese",
    "Swahili",
    "Swedish",
    "SWISS",
    "Syrian",
    "Tactile Sign Language for Deaf/Blind",
    "tagalag",
    "Tagalo",
    "Tagalog",
    "TAGALOG & URDU",
    "TAGALOG AND SPANISH",
    "Tagalog or Filipino",
    "Tagalog(Dr.)",
    "Tagaog",
    "taglog",
    "Tagolig",
    "Tai",
    "Taiwanese",
    "Taiwnese",
    "Tajik",
    "tam",
    "Tamil",
    "tamil hindi spanish",
    "TAMIL HINDI SPANISH",
    "Tatar",
    "Telegu",
    "Telgu",
    "Telugo",
    "telugu",
    "Telugu and Hindi",
    "Teochew",
    "Teweesa Sobers",
    "Thai",
    "Thia",
    "Thia and Tigrinya",
    "Tibetan",
    "Tigrinya",
    "Toi San",
    "Tonga",
    "Translation Service used",
    "translators available",
    "Tsonga",
    "Turkish",
    "Turkmen",
    "Twi",
    "Twi English",
    "Udru",
    "Uigur",
    "UKRAINAN",
    "Ukraine",
    "Ukrainian",
    "Ukranian",
    "Ukranien",
    "understands Vietnamese",
    "unlimited",
    "upon request",
    "urden",
    "Urdu",
    "Urdu & Gujarati",
    "Urdu & Spanish",
    "Urdu &Gujarati",
    "Urdu and English",
    "URDU SPANISH",
    "Urdu/Hindi",
    "Urud",
    "Using CyraCom",
    "utilize language line..over 200 languages supported",
    "Uzbek",
    "VARIES BY PROGRAM",
    "various",
    "Veitnamese",
    "Vetinamese",
    "viatnamese",
    "viet",
    "Vietanamese",
    "vietmanese",
    "Vietna",
    "Vietnam",
    "vietname",
    "Vietnames",
    "Vietnamese",
    "Vietnamese (southern dialect - only conversationally",
    "Vietnamese and spanish",
    "Vietnamese and Thai",
    "Vietnamese English",
    "Vietnamese.",
    "Vietnameses",
    "vietnamies",
    "VIETNAMSE",
    "Vietnemese",
    "Vietnemse",
    "vitenamese",
    "vitetnamese",
    "Vitnamese",
    "Volapuk",
    "WE ALSO HAVE AN ACCOUNT WITH CERTIFIED LANGUAGES INTERNATIONAL",
    "we can reach out to for interpreter. Also",
    "we can reach out to.",
    "we have an account with Certificed Languages International.",
    "We have an account with Certified Languages International",
    "we have an account with Certified Languages International.",
    "We have different languages that is spoken by the entire AuMHC staff",
    "We have employees at other cincs who speak Spanish",
    "We have employees at other location we can use for Spanish. Also",
    "We have employees who speak Spanish at our other clinic locations",
    "We have interpreters",
    "We have interpreters for all",
    "We have interpreters for all languages",
    "we have many language interpreters on staff",
    "We have other employees at other locations we can reach out to",
    "We provide interpreters for any language if need be",
    "We use a language line to interprete",
    "We will get interpreters depending on language",
    "Welsh",
    "whatever language is requested",
    "Wolof",
    "Write",
    "Xhosa",
    "Yetnamise",
    "Yiddish",
    "Yoruba",
    "Zerbaijani",
    "Zhuang",
    "Zulu"
  ]
end
