class Mhc::PracticeInformationsController < ApplicationController

  # before_action :set_practice_information, only: [:update, :destroy]

  def create
    @practice_information = PracticeInformation.new(practice_information_params)

    if @practice_information.save
      redirect_to mhc_verification_platform_path(page_tab: 'practice_info',id: params[:practice_information][:provider_attest_id]), notice: 'Practice information saved successfully.'
    else
      redirect_to mhc_verification_platform_path(page_tab: 'add_practice_info',id: params[:practice_information][:provider_attest_id]), alert: 'Failed to save practice information.'
    end
  end

  def update
    @practice_information = PracticeInformation.find(params[:id])
    if @practice_information.update(practice_information_params)
      redirect_to mhc_verification_platform_path(page_tab: 'practice_info', id: @practice_information.provider_attest_id), notice: 'Practice information updated successfully.'
    else
      render :edit, alert: 'Failed to update practice information.'
    end
  end

  def destroy
    @practice_information = PracticeInformation.find(params[:id])
    if @practice_information.destroy
      redirect_to mhc_verification_platform_path(page_tab: 'practice_info', id: params[:provider_attest_id]), notice: 'Practice information deleted successfully.'
    else
      redirect_to mhc_verification_platform_path(page_tab: 'practice_info', id: params[:provider_attest_id]), alert: 'Failed to delete practice information.'
    end
  end

  private

  # def set_practice_information
  #   @practice_information = PracticeInformation.find(params[:practice_information][:id])
  # end

  # Strong parameters for security
  def practice_information_params
    params.require(:practice_information).permit(
      :caqh_provider_practice_id, 
      :provider_attest_id, 
      :caqh_provider_attest_id,
      :practice_name,
      :address,
      :address2, :city,
      :state, 
      :answering_service_fax_number, 
      :operating_system, 
      :computer_office,
      :zip, 
      :ext_zip, 
      :county, 
      :phone_number, 
      :after_hours_phone_number, 
      :fax_number, 
      :email_address, 
      :correspondence_flag, 
      :partners_flag, 
      :other_associates_flag,
      :currently_practicing_flag,
      :start_date,
      :coverage24x7_flag,
      :practice_limitation_flag, 
      :ada_approved_flag, 
      :minority_business_flag, 
      :interpreter_available_flag, 
      :medicare_number, 
      :medicaid_number, 
      :epsdt_certified_flag, 
      :epsdt_number, 
      :practice_organization_type, 
      :phone_number2, 
      :patient_appointment_phone_number, 
      :answering_service_phone_number, 
      :pager_beeper_number, 
      :list_in_directory_flag, 
      :w9_practice_name, 
      :in_practice_flag, 
      :practice_intention_explanation, 
      :emergency_phone_number, 
      :practice_description, 
      :patients_enrolled, 
      :patient_visits, 
      :appointments_per_hour, 
      :average_waiting_time, 
      :call_response_time, 
      :electronic_billing_flag, 
      :bwc_number, 
      :workers_compensation_risk_number, 
      :ownership_description, 
      :emergency_procedure, 
      :npi, 
      :practice_type_description, 
      :service_type_description, 
      :department_name, 
      :cell_phone_number, 
      :pager_beeper_number2, 
      :end_date, :phone_extension,
      :patient_appointment_phone_extension, 
      :answering_service_phone_extension, 
      :correspondence_method, 
      :address_type_address_type_description, 
      :allied_health_practitioner_first_name, 
      :allied_health_practitioner_last_name, 
      :allied_health_practitioner_suffix, 
      :allied_health_practitioner_type_of_practitioner,
      :allied_health_practitioner_mail_stop, 
      :allied_health_practitioner_address, 
      :allied_health_practitioner_address2, 
      :allied_health_practitioner_city, 
      :allied_health_practitioner_county, 
      :allied_health_practitioner_state, 
      :allied_health_practitioner_zip_code, 
      :allied_health_practitioner_country, 
      :allied_health_practitioner_state_license, 
      :allied_health_practitioner_state_license_number, 
      :allied_health_practitioner_listed_as_pcp, 
      :country, :office_manager,
      :manager_phone_number, 
      :manager_fax_number, 
      :back_office_phone_number, 
      :type_of_practice, 
      :mail_stop, 
      :hospital_based_department_name, 
      :practice_type, 
      :group_name, 
      :group_number_with_tax_id, 
      :name_affiliated_with_tax_id, 
      :federal_tax_id, 
      :number_of_patients_weekly, 
      :total_number_of_patients, 
      :total_medicare_patients, 
      :total_medical_medicaid_patients, 
      :is_ccs, 
      :is_chdp, 
      :any_allied_health_practitioner, 
      :physician_to_nurse_ratio, 
      :physician_to_midwife_ratio, 
      :physician_to_assistant_ratio, 
      :is_employing_any_personal_practitioner, 
      :is_licensed_member_in_practice,
      :is_staff_speak_any_foreign_language,
      :radiology_services,
      :allergy_injections, 
      :age_approriate_immunizations,
      :osteopathic_manipulations,
      :ekg,
      :allergy_skin_tests,
      :flexible_sigmoidoscopy, 
      :iv_hydration_treatments,
      :care_of_minor_lacerations,
      :routine_office_gynecology,
      :tympanometry_audiometry_tests,
      :cardiac_stress_tests,
      :pulmonary_function_tests,
      :drawing_blood,
      :asthma_treatmeant,
      :physical_therapies, 
      :other_surgical_services, 
      :clinical_services_performed_not_typically_associated, 
      :clinical_services_not_performed_typically_associated, 
      :has_practice_limit_age, 
      :practice_limit_age_from, 
      :practice_limit_age_to, 
      :has_limited_gender, 
      :limited_gender, 
      :other_limitations,
      :computer_office_ibm,
      :computer_office_mac, 
      :computer_office_has_other,
      :computer_office_other,
      :os_office_wind_98,
      :os_office_wind_95,
      :os_office_wind_me, 
      :os_office_wind_2000,
      :os_office_wind_nt,
      :os_office_wind_xp,
      :os_office_mac,
      :has_os_office_other,
      :os_office_other, 
      :has_computer_has_internet_access,
      :does_participate_edi,
      :edi_network,
      :has_practice_management_software,
      :practice_management_software,
      :does_perform_surgery,
      :anesthesia_local,
      :anesthesia_regional, 
      :anesthesia_conscious_sedation, 
      :anesthesia_general,
      :anesthesia_other,
      :anesthesia_other_value,
      :anesthesia_none,
      :ambulatory_surgery_facilities, 
      :health_surgery_licensure,
      :ambulatory_health_care,
      :medicare_certification,
      :medical_quality_commission, 
      :other_certification_explanation,
      :certification_none,
      :is_laboratory_services,
      :billing_name,
      :tax_id,
      :type_of_service, 
      :clia_waiver,
      :clia_certificate,
      :clia_certificate_number,
      :clia_certificate_expiration_date, 
      :clia_certification_of_participation,
      :other_clia,
      :xray_certification_type,
      :coverage_24_hour,
      :answering_service, 
      :voice_mail_with_instruction,
      :voice_mail_with_other_instruction,
      :answering_service_company,
      :answering_service_mail_address, 
      :answering_service_mail_stop,
      :answering_service_address2,
      :answering_service_city, 
      :answering_service_country, 
      :answering_service_state,
      :answering_service_zipcode,
      :any_cover_practitioner,
      :ada_accessibility,
      :handicapped_building, 
      :handicapped_parking,
      :handicapped_restroom,
      :handicapped_other,
      :handicapped_other_explaination,
      :disabled_telephony, 
      :american_sign_language,
      :disabled_impairment_services,
      :disabled_other,
      :disabled_other_explaination, 
      :other_communication_system,
      :public_transportation,
      :public_bus,
      :public_subway,
      :public_regional_train, 
      :public_other_transportation,
      :public_other_transportation_explaination,
      :is_provide_child_care_service,
      :is_tdd, 
      :is_epsdt_certified,
      :epsdt_certificate_number,
      :is_directory_location_listed,
      :is_minority_business_enterprise, :group_npi, 
      :is_primary_location,
      :any_comments,
      :mon_time_from,
      :mon_time_to,
      :mon_closed,
      :tue_time_from,
      :tue_time_to, 
      :tue_closed, 
      :wed_time_from,
      :wed_time_to,
      :wed_closed,
      :thu_time_from,
      :thu_time_to,
      :thu_closed,
      :fri_time_from,
      :fri_time_to,
      :fri_closed,
      :sat_time_from,
      :sat_time_to,
      :sat_closed,
      :sun_time_from,
      :sun_time_to,
      :sun_closed,
      :holiday_time_from, 
      :holiday_time_to,
      :holiday_closed,

      allied_health_practitioners_attributes: [ :id, :first_name, :last_name, :suffix, :type_of_practitioner, :mail_stop, :address, :address2, :city, :county, :state, :zip_code, :country, :state_license, :state_license_number, :listed_as_pcp, :_destroy ],

      personally_employed_practitioners_attributes: [ :id, :personal_employed_first_name, :personal_employed_last_name, :personal_employed_last_name, :personal_employed_suffix_name, :personal_employed_practitioner_type, :personal_employed_state_license_number, :_destroy ],

      licensed_members_attributes: [ :id, :licensed_member_first_name, :licensed_member_last_name, :licensed_member_middle_name, :licensed_member_suffix_name, :licensed_member_practitioner_type, :licensed_member_specialty, :licensed_member_is_partner, :licensed_member_is_employing_physician,  :_destroy ],

      staff_spoken_foreign_languages_attributes: [ :id, :language, :is_spoken, :is_read, :is_write, :is_interpreter_available, :specific_language, :_destroy ],

      provider_anesthesia_administrations_attributes: [ :id, :first_name, :last_name, :suffix, :practitioner_type, :other_explaination, :is_class_a, :is_class_b, :is_class_c, :_destroy ],

      covering_practitioners_attributes: [ :id, :practitioner_name, :facility, :address, :mail_stop, :city, :address2, :country, :state, :zipcode, :phone_number, :fax_number, :email_address, :_destroy ]
    )
  end
end
